// Auto-generated from inc/arrays.php
window.SF_DATA = {
    "keys": [
        "A",
        "A♯",
        "B",
        "C",
        "C♯",
        "D",
        "D♯",
        "E",
        "F",
        "F♯",
        "G",
        "G♯",
        "A",
        "A♯",
        "B",
        "C",
        "C♯",
        "D",
        "D♯",
        "E",
        "F",
        "F♯",
        "G",
        "G♯",
        "A",
        "A♯",
        "B",
        "C",
        "C♯",
        "D",
        "D♯",
        "E",
        "F",
        "F♯",
        "G",
        "G♯"
    ],
    "allnotes": [
        "A",
        "A♯",
        "B",
        "C",
        "C♯",
        "D",
        "D♯",
        "E",
        "F",
        "F♯",
        "G",
        "G♯"
    ],
    "degrees": [
        "1",
        "♭2",
        "2",
        "♭3",
        "3",
        "4",
        "♭5",
        "5",
        "♭6",
        "6",
        "♭7",
        "7"
    ],
    "extensions": [
        "",
        "",
        "(9)",
        "",
        "",
        "(11)",
        "",
        "",
        "",
        "(13)",
        "",
        ""
    ],
    "url_note_check": [
        "k",
        "s1",
        "s2",
        "s3",
        "s4",
        "s5",
        "s6",
        "s7",
        "s8",
        "s9",
        "s10",
        "s11",
        "s12"
    ],
    "url_check": [
        "y",
        "z"
    ],
    "def_x": {
        "x": "EADGBE",
        "k": "E",
        "y": "n",
        "z": "n",
        "s1": "E",
        "s2": "B",
        "s3": "G♯",
        "s4": "E",
        "s5": "B",
        "s6": "E",
        "s7": "B",
        "s8": "G",
        "s9": "G",
        "s10": "E",
        "s11": "D",
        "s12": "A"
    },
    "scales": {
        "Major": "&hl=1&hl=2&hl=3&hl=4&hl=5&hl=6&hl=7",
        "Dorian": "&hl=1&hl=2&hl=b3&hl=4&hl=5&hl=6&hl=b7",
        "Phrygian": "&hl=1&hl=b2&hl=b3&hl=4&hl=5&hl=b6&hl=b7",
        "Lydian": "&hl=1&hl=2&hl=3&hl=b5&hl=5&hl=6&hl=7",
        "Mixolydian": "&hl=1&hl=2&hl=3&hl=4&hl=5&hl=6&hl=b7",
        "Minor": "&hl=1&hl=2&hl=b3&hl=4&hl=5&hl=b6&hl=b7",
        "Locrian": "&hl=1&hl=b2&hl=b3&hl=4&hl=b5&hl=b6&hl=b7",
        "Melodic_Minor": "&hl=1&hl=2&hl=b3&hl=4&hl=5&hl=6&hl=7",
        "Harmonic_Minor": "&hl=1&hl=2&hl=b3&hl=4&hl=5&hl=b6&hl=7",
        "Harmonic_Major": "&hl=1&hl=2&hl=3&hl=4&hl=5&hl=b6&hl=7",
        "Phrygian_Dominant": "&hl=1&hl=b2&hl=3&hl=4&hl=5&hl=b6&hl=b7",
        "Lydian_Dominant": "&hl=1&hl=2&hl=3&hl=b5&hl=5&hl=6&hl=b7",
        "Hungarian_Minor": "&hl=1&hl=2&hl=b3&hl=b5&hl=5&hl=b6&hl=7",
        "Altered": "&hl=1&hl=b2&hl=b3&hl=3&hl=b5&hl=b6&hl=b7",
        "Bebop_Dominant": "&hl=1&hl=2&hl=3&hl=4&hl=5&hl=6&hl=b7&hl=7",
        "Bebop_Major": "&hl=1&hl=2&hl=3&hl=4&hl=5&hl=b6&hl=6&hl=7",
        "Major_Pentatonic": "&hl=1&hl=2&hl=3&hl=5&hl=6",
        "Minor_Pentatonic": "&hl=1&hl=b3&hl=4&hl=5&hl=b7",
        "Blues": "&hl=1&hl=b3&hl=4&hl=b5&hl=5&hl=b7",
        "Major_Blues": "&hl=1&hl=2&hl=b3&hl=3&hl=5&hl=6",
        "Whole_Tone": "&hl=1&hl=2&hl=3&hl=b5&hl=b6&hl=b7",
        "Diminished": "&hl=1&hl=2&hl=b3&hl=4&hl=b5&hl=b6&hl=6&hl=7",
        "Half_Whole_Dim": "&hl=1&hl=b2&hl=b3&hl=3&hl=b5&hl=5&hl=6&hl=b7",
        "Hirajoshi": "&hl=1&hl=2&hl=b3&hl=5&hl=b6"
    },
    "chords": {
        "Maj": "&hl=1&hl=3&hl=5",
        "Min": "&hl=1&hl=b3&hl=5",
        "Aug": "&hl=1&hl=3&hl=b6",
        "Dim": "&hl=1&hl=b3&hl=b5",
        "Maj6": "&hl=1&hl=3&hl=5&hl=6",
        "Min6": "&hl=1&hl=b3&hl=5&hl=6",
        "Dom7": "&hl=1&hl=3&hl=5&hl=b7",
        "Min7": "&hl=1&hl=b3&hl=5&hl=b7",
        "Dim7": "&hl=1&hl=b3&hl=b5&hl=6",
        "Maj7": "&hl=1&hl=3&hl=5&hl=7"
    },
    "grid": {
        "Maj": "&hl=1&hl=3&hl=5",
        "Min": "&hl=1&hl=b3&hl=5",
        "aug": "&hl=1&hl=3&hl=b6",
        "dim": "&hl=1&hl=b3&hl=b5",
        "sus2": "&hl=1&hl=2&hl=5",
        "sus4": "&hl=1&hl=4&hl=5",
        "Maj6": "&hl=1&hl=3&hl=5&hl=6",
        "min6": "&hl=1&hl=b3&hl=5&hl=6",
        "dom7": "&hl=1&hl=3&hl=5&hl=b7",
        "min7": "&hl=1&hl=b3&hl=5&hl=b7",
        "aug7": "&hl=1&hl=3&hl=b6&hl=b7",
        "7b5": "&hl=1&hl=3&hl=b5&hl=b7",
        "dim7": "&hl=1&hl=b3&hl=b5&hl=6",
        "m7b5": "&hl=1&hl=b3&hl=b5&hl=b7",
        "Maj7": "&hl=1&hl=3&hl=5&hl=7",
        "min-Maj7": "&hl=1&hl=b3&hl=5&hl=7",
        "add9": "&hl=1&hl=2&hl=3&hl=5",
        "min9": "&hl=1&hl=2&hl=b3&hl=5",
        "6add9": "&hl=1&hl=2&hl=3&hl=5&hl=6",
        "9th": "&hl=1&hl=2&hl=3&hl=5&hl=b7",
        "7b9": "&hl=1&hl=b2&hl=3&hl=5&hl=b7",
        "Maj9": "&hl=1&hl=2&hl=3&hl=5&hl=7",
        "7#9": "&hl=1&hl=b3&hl=3&hl=5&hl=b7",
        "11th": "&hl=1&hl=2&hl=3&hl=4&hl=5&hl=b7",
        "min11": "&hl=1&hl=2&hl=b3&hl=4&hl=5&hl=b7",
        "7#11": "&hl=1&hl=2&hl=3&hl=b5&hl=5&hl=b7",
        "13th": "&hl=1&hl=2&hl=3&hl=4&hl=5&hl=6&hl=b7",
        "min13": "&hl=1&hl=2&hl=b3&hl=4&hl=5&hl=6&hl=b7",
        "Maj13": "&hl=1&hl=2&hl=3&hl=4&hl=5&hl=6&hl=7",
        "min-Maj9": "&hl=1&hl=2&hl=b3&hl=5&hl=7",
        "7b13": "&hl=1&hl=3&hl=5&hl=b6&hl=b7",
        "13b9": "&hl=1&hl=b2&hl=3&hl=5&hl=6&hl=b7",
        "sus2sus4": "&hl=1&hl=2&hl=4&hl=5",
        "add4": "&hl=1&hl=3&hl=4&hl=5"
    },
    "tunings": {
        "AAC♯EF♯AC♯E": {
            "name": "A6",
            "notes": "A A C♯ E F♯ A C♯ E",
            "url_notes": "AAC%23EF%23AC%23E",
            "rev_notes": "E C♯ A F♯ E C♯ A A",
            "dgs": "1 1 3 5 6 1 3 5",
            "rev_dgs": "5 3 1 6 5 3 1 1",
            "udgs": "1 3 5 6",
            "info": "Herb Remington",
            "strs": 8
        },
        "AC♯EF♯AC♯EF♯": {
            "name": "A6",
            "notes": "A C♯ E F♯ A C♯ E F♯",
            "url_notes": "AC%23EF%23AC%23EF%23",
            "rev_notes": "F♯ E C♯ A F♯ E C♯ A",
            "dgs": "1 3 5 6 1 3 5 6",
            "rev_dgs": "6 5 3 1 6 5 3 1",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 8
        },
        "CAC♯EF♯AC♯E": {
            "name": "A6",
            "notes": "C A C♯ E F♯ A C♯ E",
            "url_notes": "CAC%23EF%23AC%23E",
            "rev_notes": "E C♯ A F♯ E C♯ A C",
            "dgs": "♭3 1 3 5 6 1 3 5",
            "rev_dgs": "5 3 1 6 5 3 1 ♭3",
            "udgs": "1 3 5 ♭3 6",
            "info": "",
            "strs": 8
        },
        "EAC♯EF♯AC♯E": {
            "name": "A6",
            "notes": "E A C♯ E F♯ A C♯ E",
            "url_notes": "EAC%23EF%23AC%23E",
            "rev_notes": "E C♯ A F♯ E C♯ A E",
            "dgs": "5 1 3 5 6 1 3 5",
            "rev_dgs": "5 3 1 6 5 3 1 5",
            "udgs": "1 3 5 6",
            "info": "Low E",
            "strs": 8
        },
        "F♯AC♯EF♯AC♯E": {
            "name": "A6",
            "notes": "F♯ A C♯ E F♯ A C♯ E",
            "url_notes": "F%23AC%23EF%23AC%23E",
            "rev_notes": "E C♯ A F♯ E C♯ A F♯",
            "dgs": "6 1 3 5 6 1 3 5",
            "rev_dgs": "5 3 1 6 5 3 1 6",
            "udgs": "1 3 5 6",
            "info": "Leon McAuliffe",
            "strs": 8
        },
        "AC♯EGAC♯EG": {
            "name": "A7",
            "notes": "A C♯ E G A C♯ E G",
            "url_notes": "AC%23EGAC%23EG",
            "rev_notes": "G E C♯ A G E C♯ A",
            "dgs": "1 3 5 ♭7 1 3 5 ♭7",
            "rev_dgs": "♭7 5 3 1 ♭7 5 3 1",
            "udgs": "1 3 5 ♭7",
            "info": "Low A",
            "strs": 8
        },
        "EGAC♯EAC♯E": {
            "name": "A7",
            "notes": "E G A C♯ E A C♯ E",
            "url_notes": "EGAC%23EAC%23E",
            "rev_notes": "E C♯ A E C♯ A G E",
            "dgs": "5 ♭7 1 3 5 1 3 5",
            "rev_dgs": "5 3 1 5 3 1 ♭7 5",
            "udgs": "1 3 5 ♭7",
            "info": "Low E",
            "strs": 8
        },
        "G♯BDF♯AC♯EG♯": {
            "name": "Amaj7\/E9",
            "notes": "G♯ B D F♯ A C♯ E G♯",
            "url_notes": "G%23BDF%23AC%23EG%23",
            "rev_notes": "G♯ E C♯ A F♯ D B G♯",
            "dgs": "7 2 4 6 1 3 5 7",
            "rev_dgs": "7 5 3 1 6 4 2 7",
            "udgs": "1 3 5 2 4 6 7",
            "info": "",
            "strs": 8
        },
        "AC♯EG♯BC♯EG♯": {
            "name": "Amaj9",
            "notes": "A C♯ E G♯ B C♯ E G♯",
            "url_notes": "AC%23EG%23BC%23EG%23",
            "rev_notes": "G♯ E C♯ B G♯ E C♯ A",
            "dgs": "4 6 1 3 5 6 1 3",
            "rev_dgs": "3 1 6 5 3 1 6 4",
            "udgs": "1 3 5 4 6",
            "info": "",
            "strs": 8
        },
        "AAC♯EGBDF♯": {
            "name": "A11",
            "notes": "A A C♯ E G B D F♯",
            "url_notes": "AAC%23EGBDF%23",
            "rev_notes": "F♯ D B G E C♯ A A",
            "dgs": "1 1 3 5 ♭7 2 4 6",
            "rev_dgs": "6 4 2 ♭7 5 3 1 1",
            "udgs": "1 3 5 2 4 6 ♭7",
            "info": "Hanawahine 1",
            "strs": 8
        },
        "AGC♯EGBDF♯": {
            "name": "A11",
            "notes": "A G C♯ E G B D F♯",
            "url_notes": "AGC%23EGBDF%23",
            "rev_notes": "F♯ D B G E C♯ G A",
            "dgs": "1 ♭7 3 5 ♭7 2 4 6",
            "rev_dgs": "6 4 2 ♭7 5 3 ♭7 1",
            "udgs": "1 3 5 2 4 6 ♭7",
            "info": "Hanawahine 2",
            "strs": 8
        },
        "DFF♯G♯ABC♯E": {
            "name": "A Diatonic",
            "notes": "D F F♯ G♯ A B C♯ E",
            "url_notes": "DFF%23G%23ABC%23E",
            "rev_notes": "E C♯ B A G♯ F♯ F D",
            "dgs": "4 ♭6 6 7 1 2 3 5",
            "rev_dgs": "5 3 2 1 7 6 ♭6 4",
            "udgs": "1 3 5 2 ♭6 6 7",
            "info": "John Ely",
            "strs": 8
        },
        "A♯DFGA♯DFG": {
            "name": "A♯6",
            "notes": "A♯ D F G A♯ D F G",
            "url_notes": "A%23DFGA%23DFG",
            "rev_notes": "G F D A♯ G F D A♯",
            "dgs": "1 3 5 6 1 3 5 6",
            "rev_dgs": "6 5 3 1 6 5 3 1",
            "udgs": "1 3 5 6",
            "info": "High 6",
            "strs": 8
        },
        "GA♯DFGA♯DF": {
            "name": "A♯6",
            "notes": "G A♯ D F G A♯ D F",
            "url_notes": "GA%23DFGA%23DF",
            "rev_notes": "F D A♯ G F D A♯ G",
            "dgs": "6 1 3 5 6 1 3 5",
            "rev_dgs": "5 3 1 6 5 3 1 6",
            "udgs": "1 3 5 6",
            "info": "Western Swing",
            "strs": 8
        },
        "BD♯F♯G♯BD♯F♯G♯": {
            "name": "B6",
            "notes": "B D♯ F♯ G♯ B D♯ F♯ G♯",
            "url_notes": "BD%23F%23G%23BD%23F%23G%23",
            "rev_notes": "G♯ F♯ D♯ B G♯ F♯ D♯ B",
            "dgs": "1 3 5 6 1 3 5 6",
            "rev_dgs": "6 5 3 1 6 5 3 1",
            "udgs": "1 3 5 6",
            "info": "High 6",
            "strs": 8
        },
        "G♯BD♯F♯G♯BD♯F♯": {
            "name": "B6",
            "notes": "G♯ B D♯ F♯ G♯ B D♯ F♯",
            "url_notes": "G%23BD%23F%23G%23BD%23F%23",
            "rev_notes": "F♯ D♯ B G♯ F♯ D♯ B G♯",
            "dgs": "6 1 3 5 6 1 3 5",
            "rev_dgs": "5 3 1 6 5 3 1 6",
            "udgs": "1 3 5 6",
            "info": "Western Swing",
            "strs": 8
        },
        "ABC♯D♯F♯AC♯E": {
            "name": "B11",
            "notes": "A B C♯ D♯ F♯ A C♯ E",
            "url_notes": "ABC%23D%23F%23AC%23E",
            "rev_notes": "E C♯ A F♯ D♯ C♯ B A",
            "dgs": "♭7 1 2 3 5 ♭7 2 4",
            "rev_dgs": "4 2 ♭7 5 3 2 1 ♭7",
            "udgs": "1 3 5 2 4 ♭7",
            "info": "Frank Baum",
            "strs": 8
        },
        "BABD♯F♯AC♯E": {
            "name": "B11",
            "notes": "B A B D♯ F♯ A C♯ E",
            "url_notes": "BABD%23F%23AC%23E",
            "rev_notes": "E C♯ A F♯ D♯ B A B",
            "dgs": "1 ♭7 1 3 5 ♭7 2 4",
            "rev_dgs": "4 2 ♭7 5 3 1 ♭7 1",
            "udgs": "1 3 5 2 4 ♭7",
            "info": "Henriques",
            "strs": 8
        },
        "BAC♯D♯F♯AC♯E": {
            "name": "B11",
            "notes": "B A C♯ D♯ F♯ A C♯ E",
            "url_notes": "BAC%23D%23F%23AC%23E",
            "rev_notes": "E C♯ A F♯ D♯ C♯ A B",
            "dgs": "1 ♭7 2 3 5 ♭7 2 4",
            "rev_dgs": "4 2 ♭7 5 3 2 ♭7 1",
            "udgs": "1 3 5 2 4 ♭7",
            "info": "Drop-string A6",
            "strs": 8
        },
        "BF♯BD♯F♯AC♯E": {
            "name": "B11",
            "notes": "B F♯ B D♯ F♯ A C♯ E",
            "url_notes": "BF%23BD%23F%23AC%23E",
            "rev_notes": "E C♯ A F♯ D♯ B F♯ B",
            "dgs": "1 5 1 3 5 ♭7 2 4",
            "rev_dgs": "4 2 ♭7 5 3 1 5 1",
            "udgs": "1 3 5 2 4 ♭7",
            "info": "",
            "strs": 8
        },
        "F♯ABD♯F♯AC♯E": {
            "name": "B11",
            "notes": "F♯ A B D♯ F♯ A C♯ E",
            "url_notes": "F%23ABD%23F%23AC%23E",
            "rev_notes": "E C♯ A F♯ D♯ B A F♯",
            "dgs": "5 ♭7 1 3 5 ♭7 2 4",
            "rev_dgs": "4 2 ♭7 5 3 1 ♭7 5",
            "udgs": "1 3 5 2 4 ♭7",
            "info": "",
            "strs": 8
        },
        "ACEGACEG": {
            "name": "C6",
            "notes": "A C E G A C E G",
            "url_notes": "ACEGACEG",
            "rev_notes": "G E C A G E C A",
            "dgs": "6 1 3 5 6 1 3 5",
            "rev_dgs": "5 3 1 6 5 3 1 6",
            "udgs": "1 3 5 6",
            "info": "Standard-8",
            "strs": 8
        },
        "GACEGACE": {
            "name": "C6",
            "notes": "G A C E G A C E",
            "url_notes": "GACEGACE",
            "rev_notes": "E C A G E C A G",
            "dgs": "5 6 1 3 5 6 1 3",
            "rev_dgs": "3 1 6 5 3 1 6 5",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 8
        },
        "ACC♯EGACE": {
            "name": "C6\/A7",
            "notes": "A C C♯ E G A C E",
            "url_notes": "ACC%23EGACE",
            "rev_notes": "E C A G E C♯ C A",
            "dgs": "6 1 ♭2 3 5 6 1 3",
            "rev_dgs": "3 1 6 5 3 ♭2 1 6",
            "udgs": "1 3 5 ♭2 6",
            "info": "Jerry Byrd",
            "strs": 8
        },
        "BAC♯EGACE": {
            "name": "C6\/A7",
            "notes": "B A C♯ E G A C E",
            "url_notes": "BAC%23EGACE",
            "rev_notes": "E C A G E C♯ A B",
            "dgs": "7 6 ♭2 3 5 6 1 3",
            "rev_dgs": "3 1 6 5 3 ♭2 6 7",
            "udgs": "1 3 5 ♭2 6 7",
            "info": "Joaquin High E",
            "strs": 8
        },
        "bC♯EGACEG": {
            "name": "C6\/A7",
            "notes": "b C♯ E G A C E G",
            "url_notes": "bC%23EGACEG",
            "rev_notes": "G E C A G E C♯ b",
            "dgs": "7 ♭2 3 5 6 1 3 5",
            "rev_dgs": "5 3 1 6 5 3 ♭2 7",
            "udgs": "1 3 5 ♭2 6 7",
            "info": "Joaquin High G",
            "strs": 8
        },
        "bAC♯EGACE": {
            "name": "C6\/A7",
            "notes": "b A C♯ E G A C E",
            "url_notes": "bAC%23EGACE",
            "rev_notes": "E C A G E C♯ A b",
            "dgs": "7 6 ♭2 3 5 6 1 3",
            "rev_dgs": "3 1 6 5 3 ♭2 6 7",
            "udgs": "1 3 5 ♭2 6 7",
            "info": "hi 8 str",
            "strs": 8
        },
        "CGCEGA♯DF": {
            "name": "C11",
            "notes": "C G C E G A♯ D F",
            "url_notes": "CGCEGA%23DF",
            "rev_notes": "F D A♯ G E C G C",
            "dgs": "1 5 1 3 5 ♭7 2 4",
            "rev_dgs": "4 2 ♭7 5 3 1 5 1",
            "udgs": "1 3 5 2 4 ♭7",
            "info": "",
            "strs": 8
        },
        "A♯CEGACEG": {
            "name": "C13",
            "notes": "A♯ C E G A C E G",
            "url_notes": "A%23CEGACEG",
            "rev_notes": "G E C A G E C A♯",
            "dgs": "♭7 1 3 5 6 1 3 5",
            "rev_dgs": "5 3 1 6 5 3 1 ♭7",
            "udgs": "1 3 5 6 ♭7",
            "info": "Junior Brown",
            "strs": 8
        },
        "CA♯CEGACE": {
            "name": "C13",
            "notes": "C A♯ C E G A C E",
            "url_notes": "CA%23CEGACE",
            "rev_notes": "E C A G E C A♯ C",
            "dgs": "1 ♭7 1 3 5 6 1 3",
            "rev_dgs": "3 1 6 5 3 1 ♭7 1",
            "udgs": "1 3 5 6 ♭7",
            "info": "Slim Yamaguchi",
            "strs": 8
        },
        "GA♯CEGACE": {
            "name": "C13",
            "notes": "G A♯ C E G A C E",
            "url_notes": "GA%23CEGACE",
            "rev_notes": "E C A G E C A♯ G",
            "dgs": "5 ♭7 1 3 5 6 1 3",
            "rev_dgs": "3 1 6 5 3 1 ♭7 5",
            "udgs": "1 3 5 6 ♭7",
            "info": "",
            "strs": 8
        },
        "f♯d♯A♯C♯EG♯C♯E": {
            "name": "C♯m11\/F♯9",
            "notes": "f♯ d♯ A♯ C♯ E G♯ C♯ E",
            "url_notes": "f%23d%23A%23C%23EG%23C%23E",
            "rev_notes": "E C♯ G♯ E C♯ A♯ d♯ f♯",
            "dgs": "4 2 6 1 ♭3 5 1 ♭3",
            "rev_dgs": "♭3 1 5 ♭3 1 6 2 4",
            "udgs": "1 ♭3 5 2 4 6",
            "info": "Joaquin Murphey\"s C♯m",
            "strs": 8
        },
        "ABDF♯ABDF♯": {
            "name": "D6",
            "notes": "A B D F♯ A B D F♯",
            "url_notes": "ABDF%23ABDF%23",
            "rev_notes": "F♯ D B A F♯ D B A",
            "dgs": "5 6 1 3 5 6 1 3",
            "rev_dgs": "3 1 6 5 3 1 6 5",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 8
        },
        "F♯ABDF♯ABD": {
            "name": "D6",
            "notes": "F♯ A B D F♯ A B D",
            "url_notes": "F%23ABDF%23ABD",
            "rev_notes": "D B A F♯ D B A F♯",
            "dgs": "3 5 6 1 3 5 6 1",
            "rev_dgs": "1 6 5 3 1 6 5 3",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 8
        },
        "DACEF♯ACE": {
            "name": "D9",
            "notes": "D A C E F♯ A C E",
            "url_notes": "DACEF%23ACE",
            "rev_notes": "E C A F♯ E C A D",
            "dgs": "1 5 ♭7 2 3 5 ♭7 2",
            "rev_dgs": "2 ♭7 5 3 2 ♭7 5 1",
            "udgs": "1 3 5 2 ♭7",
            "info": "John Ely",
            "strs": 8
        },
        "DF♯ACEF♯AD": {
            "name": "D9",
            "notes": "D F♯ A C E F♯ A D",
            "url_notes": "DF%23ACEF%23AD",
            "rev_notes": "D A F♯ E C A F♯ D",
            "dgs": "1 3 5 ♭7 2 3 5 1",
            "rev_dgs": "1 5 3 2 ♭7 5 3 1",
            "udgs": "1 3 5 2 ♭7",
            "info": "",
            "strs": 8
        },
        "F♯ACDF♯ACE": {
            "name": "D9",
            "notes": "F♯ A C D F♯ A C E",
            "url_notes": "F%23ACDF%23ACE",
            "rev_notes": "E C A F♯ D C A F♯",
            "dgs": "3 5 ♭7 1 3 5 ♭7 2",
            "rev_dgs": "2 ♭7 5 3 1 ♭7 5 3",
            "udgs": "1 3 5 2 ♭7",
            "info": "",
            "strs": 8
        },
        "F♯ACEF♯ACE": {
            "name": "D9",
            "notes": "F♯ A C E F♯ A C E",
            "url_notes": "F%23ACEF%23ACE",
            "rev_notes": "E C A F♯ E C A F♯",
            "dgs": "3 5 ♭7 2 3 5 ♭7 2",
            "rev_dgs": "2 ♭7 5 3 2 ♭7 5 3",
            "udgs": "3 5 2 ♭7",
            "info": "No root\/DropString C6",
            "strs": 8
        },
        "F♯ACEGACE": {
            "name": "D9",
            "notes": "F♯ A C E G A C E",
            "url_notes": "F%23ACEGACE",
            "rev_notes": "E C A G E C A F♯",
            "dgs": "3 5 ♭7 2 4 5 ♭7 2",
            "rev_dgs": "2 ♭7 5 4 2 ♭7 5 3",
            "udgs": "3 5 2 4 ♭7",
            "info": "No Root\/Joaquin Murphey",
            "strs": 8
        },
        "DADF♯ACEG": {
            "name": "D11",
            "notes": "D A D F♯ A C E G",
            "url_notes": "DADF%23ACEG",
            "rev_notes": "G E C A F♯ D A D",
            "dgs": "1 5 1 3 5 ♭7 2 4",
            "rev_dgs": "4 2 ♭7 5 3 1 5 1",
            "udgs": "1 3 5 2 4 ♭7",
            "info": "",
            "strs": 8
        },
        "A♯CD♯GA♯CD♯G": {
            "name": "D♯6",
            "notes": "A♯ C D♯ G A♯ C D♯ G",
            "url_notes": "A%23CD%23GA%23CD%23G",
            "rev_notes": "G D♯ C A♯ G D♯ C A♯",
            "dgs": "5 6 1 3 5 6 1 3",
            "rev_dgs": "3 1 6 5 3 1 6 5",
            "udgs": "1 3 5 6",
            "info": "Low A♯",
            "strs": 8
        },
        "BC♯EG♯BC♯EG♯": {
            "name": "E6",
            "notes": "B C♯ E G♯ B C♯ E G♯",
            "url_notes": "BC%23EG%23BC%23EG%23",
            "rev_notes": "G♯ E C♯ B G♯ E C♯ B",
            "dgs": "5 6 1 3 5 6 1 3",
            "rev_dgs": "3 1 6 5 3 1 6 5",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 8
        },
        "G♯BC♯EG♯BC♯E": {
            "name": "E6",
            "notes": "G♯ B C♯ E G♯ B C♯ E",
            "url_notes": "G%23BC%23EG%23BC%23E",
            "rev_notes": "E C♯ B G♯ E C♯ B G♯",
            "dgs": "3 5 6 1 3 5 6 1",
            "rev_dgs": "1 6 5 3 1 6 5 3",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 8
        },
        "EBDEG♯BEG♯": {
            "name": "E7",
            "notes": "E B D E G♯ B E G♯",
            "url_notes": "EBDEG%23BEG%23",
            "rev_notes": "G♯ E B G♯ E D B E",
            "dgs": "1 5 ♭7 1 3 5 1 3",
            "rev_dgs": "3 1 5 3 1 ♭7 5 1",
            "udgs": "1 3 5 ♭7",
            "info": "Low E",
            "strs": 8
        },
        "EG♯BDEG♯BE": {
            "name": "E7",
            "notes": "E G♯ B D E G♯ B E",
            "url_notes": "EG%23BDEG%23BE",
            "rev_notes": "E B G♯ E D B G♯ E",
            "dgs": "1 3 5 ♭7 1 3 5 1",
            "rev_dgs": "1 5 3 1 ♭7 5 3 1",
            "udgs": "1 3 5 ♭7",
            "info": "Hawaiian And Country",
            "strs": 8
        },
        "G♯BDEG♯BEG♯": {
            "name": "E7",
            "notes": "G♯ B D E G♯ B E G♯",
            "url_notes": "G%23BDEG%23BEG%23",
            "rev_notes": "G♯ E B G♯ E D B G♯",
            "dgs": "3 5 ♭7 1 3 5 1 3",
            "rev_dgs": "3 1 5 3 1 ♭7 5 3",
            "udgs": "1 3 5 ♭7",
            "info": "Low\/High G♯",
            "strs": 8
        },
        "EG♯BDF♯AC♯E": {
            "name": "E7\/A6",
            "notes": "E G♯ B D F♯ A C♯ E",
            "url_notes": "EG%23BDF%23AC%23E",
            "rev_notes": "E C♯ A F♯ D B G♯ E",
            "dgs": "1 3 5 ♭7 2 4 6 1",
            "rev_dgs": "1 6 4 2 ♭7 5 3 1",
            "udgs": "1 3 5 2 4 6 ♭7",
            "info": "Scott Martin",
            "strs": 8
        },
        "BG♯DEF♯G♯BE": {
            "name": "E9",
            "notes": "B G♯ D E F♯ G♯ B E",
            "url_notes": "BG%23DEF%23G%23BE",
            "rev_notes": "E B G♯ F♯ E D G♯ B",
            "dgs": "5 3 ♭7 1 2 3 5 1",
            "rev_dgs": "1 5 3 2 1 ♭7 3 5",
            "udgs": "1 3 5 2 ♭7",
            "info": "",
            "strs": 8
        },
        "EBDEF♯G♯BE": {
            "name": "E9",
            "notes": "E B D E F♯ G♯ B E",
            "url_notes": "EBDEF%23G%23BE",
            "rev_notes": "E B G♯ F♯ E D B E",
            "dgs": "1 5 ♭7 1 2 3 5 1",
            "rev_dgs": "1 5 3 2 1 ♭7 5 1",
            "udgs": "1 3 5 2 ♭7",
            "info": "",
            "strs": 8
        },
        "EG♯BDF♯G♯BE": {
            "name": "E9",
            "notes": "E G♯ B D F♯ G♯ B E",
            "url_notes": "EG%23BDF%23G%23BE",
            "rev_notes": "E B G♯ F♯ D B G♯ E",
            "dgs": "1 3 5 ♭7 2 3 5 1",
            "rev_dgs": "1 5 3 2 ♭7 5 3 1",
            "udgs": "1 3 5 2 ♭7",
            "info": "",
            "strs": 8
        },
        "G♯BDEF♯G♯BE": {
            "name": "E9",
            "notes": "G♯ B D E F♯ G♯ B E",
            "url_notes": "G%23BDEF%23G%23BE",
            "rev_notes": "E B G♯ F♯ E D B G♯",
            "dgs": "3 5 ♭7 1 2 3 5 1",
            "rev_dgs": "1 5 3 2 1 ♭7 5 3",
            "udgs": "1 3 5 2 ♭7",
            "info": "",
            "strs": 8
        },
        "BG♯DEG♯BC♯E": {
            "name": "E13",
            "notes": "B G♯ D E G♯ B C♯ E",
            "url_notes": "BG%23DEG%23BC%23E",
            "rev_notes": "E C♯ B G♯ E D G♯ B",
            "dgs": "5 3 ♭7 1 3 5 6 1",
            "rev_dgs": "1 6 5 3 1 ♭7 3 5",
            "udgs": "1 3 5 6 ♭7",
            "info": "",
            "strs": 8
        },
        "DEF♯G♯BC♯EG♯": {
            "name": "E13",
            "notes": "D E F♯ G♯ B C♯ E G♯",
            "url_notes": "DEF%23G%23BC%23EG%23",
            "rev_notes": "G♯ E C♯ B G♯ F♯ E D",
            "dgs": "♭7 1 2 3 5 6 1 3",
            "rev_dgs": "3 1 6 5 3 2 1 ♭7",
            "udgs": "1 3 5 2 6 ♭7",
            "info": "High G♯",
            "strs": 8
        },
        "EBDEF♯G♯C♯E": {
            "name": "E13",
            "notes": "E B D E F♯ G♯ C♯ E",
            "url_notes": "EBDEF%23G%23C%23E",
            "rev_notes": "E C♯ G♯ F♯ E D B E",
            "dgs": "1 5 ♭7 1 2 3 6 1",
            "rev_dgs": "1 6 3 2 1 ♭7 5 1",
            "udgs": "1 3 5 2 6 ♭7",
            "info": "C♯m9",
            "strs": 8
        },
        "EBDEG♯BC♯E": {
            "name": "E13",
            "notes": "E B D E G♯ B C♯ E",
            "url_notes": "EBDEG%23BC%23E",
            "rev_notes": "E C♯ B G♯ E D B E",
            "dgs": "1 5 ♭7 1 3 5 6 1",
            "rev_dgs": "1 6 5 3 1 ♭7 5 1",
            "udgs": "1 3 5 6 ♭7",
            "info": "Harry Brooker",
            "strs": 8
        },
        "EBDF♯G♯BC♯E": {
            "name": "E13",
            "notes": "E B D F♯ G♯ B C♯ E",
            "url_notes": "EBDF%23G%23BC%23E",
            "rev_notes": "E C♯ B G♯ F♯ D B E",
            "dgs": "1 5 ♭7 2 3 5 6 1",
            "rev_dgs": "1 6 5 3 2 ♭7 5 1",
            "udgs": "1 3 5 2 6 ♭7",
            "info": "Western Swing",
            "strs": 8
        },
        "EDEG♯BC♯EG♯": {
            "name": "E13",
            "notes": "E D E G♯ B C♯ E G♯",
            "url_notes": "EDEG%23BC%23EG%23",
            "rev_notes": "G♯ E C♯ B G♯ E D E",
            "dgs": "1 ♭7 1 3 5 6 1 3",
            "rev_dgs": "3 1 6 5 3 1 ♭7 1",
            "udgs": "1 3 5 6 ♭7",
            "info": "Don Helms Little Roy Wiggins",
            "strs": 8
        },
        "EG♯BDEG♯C♯E": {
            "name": "E13\/C♯m7",
            "notes": "E G♯ B D E G♯ C♯ E",
            "url_notes": "EG%23BDEG%23C%23E",
            "rev_notes": "E C♯ G♯ E D B G♯ E",
            "dgs": "1 3 5 ♭7 1 3 6 1",
            "rev_dgs": "1 6 3 1 ♭7 5 3 1",
            "udgs": "1 3 5 6 ♭7",
            "info": "",
            "strs": 8
        },
        "EG♯BDF♯G♯C♯E": {
            "name": "E13",
            "notes": "E G♯ B D F♯ G♯ C♯ E",
            "url_notes": "EG%23BDF%23G%23C%23E",
            "rev_notes": "E C♯ G♯ F♯ D B G♯ E",
            "dgs": "1 3 5 ♭7 2 3 6 1",
            "rev_dgs": "1 6 3 2 ♭7 5 3 1",
            "udgs": "1 3 5 2 6 ♭7",
            "info": "",
            "strs": 8
        },
        "EG♯DF♯G♯BC♯E": {
            "name": "E13",
            "notes": "E G♯ D F♯ G♯ B C♯ E",
            "url_notes": "EG%23DF%23G%23BC%23E",
            "rev_notes": "E C♯ B G♯ F♯ D G♯ E",
            "dgs": "1 3 ♭7 2 3 5 6 1",
            "rev_dgs": "1 6 5 3 2 ♭7 3 1",
            "udgs": "1 3 5 2 6 ♭7",
            "info": "Leon McAuliffe Bobby Koefer",
            "strs": 8
        },
        "G♯BDEG♯BC♯E": {
            "name": "E13",
            "notes": "G♯ B D E G♯ B C♯ E",
            "url_notes": "G%23BDEG%23BC%23E",
            "rev_notes": "E C♯ B G♯ E D B G♯",
            "dgs": "3 5 ♭7 1 3 5 6 1",
            "rev_dgs": "1 6 5 3 1 ♭7 5 3",
            "udgs": "1 3 5 6 ♭7",
            "info": "Low G♯",
            "strs": 8
        },
        "EG♯BD♯F♯BC♯E": {
            "name": "Emaj13",
            "notes": "E G♯ B D♯ F♯ B C♯ E",
            "url_notes": "EG%23BD%23F%23BC%23E",
            "rev_notes": "E C♯ B F♯ D♯ B G♯ E",
            "dgs": "1 3 5 7 2 5 6 1",
            "rev_dgs": "1 6 5 2 7 5 3 1",
            "udgs": "1 3 5 2 6 7",
            "info": "",
            "strs": 8
        },
        "DFACDFAC": {
            "name": "F6",
            "notes": "D F A C D F A C",
            "url_notes": "DFACDFAC",
            "rev_notes": "C A F D C A F D",
            "dgs": "6 1 3 5 6 1 3 5",
            "rev_dgs": "5 3 1 6 5 3 1 6",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 8
        },
        "FCD♯GFADF": {
            "name": "F9",
            "notes": "F C D♯ G F A D F",
            "url_notes": "FCD%23GFADF",
            "rev_notes": "F D A F G D♯ C F",
            "dgs": "1 5 ♭7 2 1 3 6 1",
            "rev_dgs": "1 6 3 1 2 ♭7 5 1",
            "udgs": "1 3 5 2 6 ♭7",
            "info": "Kayton Roberts",
            "strs": 8
        },
        "FACEGACE": {
            "name": "Fmaj9",
            "notes": "F A C E G A C E",
            "url_notes": "FACEGACE",
            "rev_notes": "E C A G E C A F",
            "dgs": "1 3 5 7 2 3 5 7",
            "rev_dgs": "7 5 3 2 7 5 3 1",
            "udgs": "1 3 5 2 7",
            "info": "",
            "strs": 8
        },
        "G♯C♯F♯A♯EG♯C♯E": {
            "name": "F♯9",
            "notes": "G♯ C♯ F♯ A♯ E G♯ C♯ E",
            "url_notes": "G%23C%23F%23A%23EG%23C%23E",
            "rev_notes": "E C♯ G♯ E A♯ F♯ C♯ G♯",
            "dgs": "2 5 1 3 ♭7 2 5 ♭7",
            "rev_dgs": "♭7 5 2 ♭7 3 1 5 2",
            "udgs": "1 3 5 2 ♭7",
            "info": "Jerry Byrd",
            "strs": 8
        },
        "f♯d♯F♯A♯EG♯C♯E": {
            "name": "F♯13",
            "notes": "f♯ d♯ F♯ A♯ E G♯ C♯ E",
            "url_notes": "f%23d%23F%23A%23EG%23C%23E",
            "rev_notes": "E C♯ G♯ E A♯ F♯ d♯ f♯",
            "dgs": "1 6 1 3 ♭7 2 5 ♭7",
            "rev_dgs": "♭7 5 2 ♭7 3 1 6 1",
            "udgs": "1 3 5 2 4 ♭7",
            "info": "Herb Remington",
            "strs": 8
        },
        "DGBDGBDG": {
            "name": "G",
            "notes": "D G B D G B D G",
            "url_notes": "DGBDGBDG",
            "rev_notes": "G D B G D B G D",
            "dgs": "5 1 3 5 1 3 5 1",
            "rev_dgs": "1 5 3 1 5 3 1 5",
            "udgs": "1 3 5",
            "info": "",
            "strs": 8
        },
        "BDEGBDEG": {
            "name": "G6",
            "notes": "B D E G B D E G",
            "url_notes": "BDEGBDEG",
            "rev_notes": "G E D B G E D B",
            "dgs": "3 5 6 1 3 5 6 1",
            "rev_dgs": "1 6 5 3 1 6 5 3",
            "udgs": "1 3 5 6",
            "info": "High G",
            "strs": 8
        },
        "EGBDEGBD": {
            "name": "G6",
            "notes": "E G B D E G B D",
            "url_notes": "EGBDEGBD",
            "rev_notes": "D B G E D B G E",
            "dgs": "6 1 3 5 6 1 3 5",
            "rev_dgs": "5 3 1 6 5 3 1 6",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 8
        },
        "GBDEGBDE": {
            "name": "G6",
            "notes": "G B D E G B D E",
            "url_notes": "GBDEGBDE",
            "rev_notes": "E D B G E D B G",
            "dgs": "1 3 5 6 1 3 5 6",
            "rev_dgs": "6 5 3 1 6 5 3 1",
            "udgs": "1 3 5 6",
            "info": "High 6",
            "strs": 8
        },
        "EGBDGBDG": {
            "name": "GDobro\/6",
            "notes": "E G B D G B D G",
            "url_notes": "EGBDGBDG",
            "rev_notes": "G D B G D B G E",
            "dgs": "6 1 3 5 1 3 5 1",
            "rev_dgs": "1 5 3 1 5 3 1 6",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 8
        },
        "EGBDGBDF": {
            "name": "G7\/6",
            "notes": "E G B D G B D F",
            "url_notes": "EGBDGBDF",
            "rev_notes": "F D B G D B G E",
            "dgs": "6 1 3 5 1 3 5 ♭7",
            "rev_dgs": "♭7 5 3 1 5 3 1 6",
            "udgs": "1 3 5 6 ♭7",
            "info": "",
            "strs": 8
        },
        "CGEGBDEF♯": {
            "name": "Gmaj7\/C",
            "notes": "C G E G B D E F♯",
            "url_notes": "CGEGBDEF%23",
            "rev_notes": "F♯ E D B G E G C",
            "dgs": "4 1 6 1 3 5 6 7",
            "rev_dgs": "7 6 5 3 1 6 1 4",
            "udgs": "1 3 5 4 6 7",
            "info": "Dick Sanft",
            "strs": 8
        },
        "GBDEFBDE": {
            "name": "G13",
            "notes": "G B D E F B D E",
            "url_notes": "GBDEFBDE",
            "rev_notes": "E D B F E D B G",
            "dgs": "1 3 5 6 ♭7 3 5 6",
            "rev_dgs": "6 5 3 ♭7 6 5 3 1",
            "udgs": "1 3 5 6 ♭7",
            "info": "",
            "strs": 8
        },
        "GBDEFGBD": {
            "name": "G13",
            "notes": "G B D E F G B D",
            "url_notes": "GBDEFGBD",
            "rev_notes": "D B G F E D B G",
            "dgs": "1 3 5 6 ♭7 1 3 5",
            "rev_dgs": "5 3 1 ♭7 6 5 3 1",
            "udgs": "1 3 5 6 ♭7",
            "info": "",
            "strs": 8
        },
        "EGBDFACE": {
            "name": "G13\/9\/11",
            "notes": "E G B D F A C E",
            "url_notes": "EGBDFACE",
            "rev_notes": "E C A F D B G E",
            "dgs": "6 1 3 5 ♭7 2 4 6",
            "rev_dgs": "6 4 2 ♭7 5 3 1 6",
            "udgs": "1 3 5 2 4 6 ♭7",
            "info": "",
            "strs": 8
        },
        "EGBDGBDF♯": {
            "name": "Gmaj13",
            "notes": "E G B D G B D F♯",
            "url_notes": "EGBDGBDF%23",
            "rev_notes": "F♯ D B G D B G E",
            "dgs": "6 1 3 5 1 3 5 7",
            "rev_dgs": "7 5 3 1 5 3 1 6",
            "udgs": "1 3 5 6 7",
            "info": "no 2",
            "strs": 8
        },
        "GBDF♯ADEG": {
            "name": "Gmaj13",
            "notes": "G B D F♯ A D E G",
            "url_notes": "GBDF%23ADEG",
            "rev_notes": "G E D A F♯ D B G",
            "dgs": "1 3 5 7 2 5 6 1",
            "rev_dgs": "1 6 5 2 7 5 3 1",
            "udgs": "1 3 5 2 6 7",
            "info": "",
            "strs": 8
        },
        "EEEADGBE": {
            "name": "GitE",
            "notes": "E E E A D G B E",
            "url_notes": "EEEADGBE",
            "rev_notes": "E B G D A E E E",
            "dgs": "1 1 1 4 ♭7 ♭3 5 1",
            "rev_dgs": "1 5 ♭3 ♭7 4 1 1 1 ",
            "udgs": "1 ♭3 4 5 ♭7",
            "info": "Git option",
            "strs": 8
        },
        "BBBEADF♯B": {
            "name": "BariB",
            "notes": "B B B E A D F♯ B",
            "url_notes": "BBBEADF%23B",
            "rev_notes": "B F♯ D A E B B B",
            "dgs": "1 1 1 4 ♭7 ♭3 5 1",
            "rev_dgs": "1 5 ♭3 ♭7 4 1 1 1",
            "udgs": "1 ♭3 4 5 ♭7",
            "info": "Bari option",
            "strs": 8
        },
        "EADGBE": {
            "name": "E-Standard",
            "notes": "E A D G B E",
            "url_notes": "EADGBE",
            "rev_notes": "E B G D A E",
            "dgs": "1 4 ♭7 ♭3 5 1",
            "rev_dgs": "1 5 ♭3 ♭7 4 1",
            "udgs": "1 ♭3 4 5 ♭7",
            "info": "",
            "strs": 6
        },
        "BEADF♯B": {
            "name": "B-Bari",
            "notes": "B E A D F♯ B",
            "url_notes": "BEADF%23B",
            "rev_notes": "B F♯ D A E B",
            "dgs": "1 4 ♭7 ♭3 5 1",
            "rev_dgs": "1 5 ♭3 ♭7 4 1",
            "udgs": "1 ♭3 4 5 ♭7",
            "info": "",
            "strs": 6
        },
        "AC♯EAC♯E": {
            "name": "A",
            "notes": "A C♯ E A C♯ E",
            "url_notes": "AC%23EAC%23E",
            "rev_notes": "E C♯ A E C♯ A",
            "dgs": "1 3 5 1 3 5",
            "rev_dgs": "5 3 1 5 3 1",
            "udgs": "1 3 5",
            "info": "",
            "strs": 6
        },
        "EAEAC♯E": {
            "name": "A",
            "notes": "E A E A C♯ E",
            "url_notes": "EAEAC%23E",
            "rev_notes": "E C♯ A E A E",
            "dgs": "5 1 5 1 3 5",
            "rev_dgs": "5 3 1 5 1 5",
            "udgs": "1 3 5",
            "info": "",
            "strs": 6
        },
        "C♯EF♯AC♯E": {
            "name": "A6",
            "notes": "C♯ E F♯ A C♯ E",
            "url_notes": "C%23EF%23AC%23E",
            "rev_notes": "E C♯ A F♯ E C♯",
            "dgs": "3 5 6 1 3 5",
            "rev_dgs": "5 3 1 6 5 3",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "ACEGBD": {
            "name": "Am11",
            "notes": "A C E G B D",
            "url_notes": "ACEGBD",
            "rev_notes": "D B G E C A",
            "dgs": "1 ♭3 5 ♭7 2 4",
            "rev_dgs": "4 2 ♭7 5 ♭3 1",
            "udgs": "1 2 ♭3 4 5 ♭7",
            "info": "",
            "strs": 6
        },
        "BDF♯ABD": {
            "name": "A♯7",
            "notes": "B D F♯ A B D",
            "url_notes": "BDF%23ABD",
            "rev_notes": "D B A F♯ D B",
            "dgs": "2 4 6 1 2 4",
            "rev_dgs": "4 2 1 6 4 2",
            "udgs": "1 2 4 6",
            "info": "",
            "strs": 6
        },
        "BF♯BD♯F♯B": {
            "name": "B",
            "notes": "B F♯ B D♯ F♯ B",
            "url_notes": "BF%23BD%23F%23B",
            "rev_notes": "B F♯ D♯ B F♯ B",
            "dgs": "1 5 1 3 5 1",
            "rev_dgs": "1 5 3 1 5 1",
            "udgs": "1 3 5",
            "info": "",
            "strs": 6
        },
        "BD♯F♯AC♯E": {
            "name": "B11",
            "notes": "B D♯ F♯ A C♯ E",
            "url_notes": "BD%23F%23AC%23E",
            "rev_notes": "E C♯ A F♯ D♯ B",
            "dgs": "1 3 5 ♭7 2 4",
            "rev_dgs": "4 2 ♭7 5 3 1",
            "udgs": "1 3 5 2 4 ♭7",
            "info": "",
            "strs": 6
        },
        "C♯D♯F♯AC♯E": {
            "name": "B11",
            "notes": "C♯ D♯ F♯ A C♯ E",
            "url_notes": "C%23D%23F%23AC%23E",
            "rev_notes": "E C♯ A F♯ D♯ C♯",
            "dgs": "2 3 5 ♭7 2 4",
            "rev_dgs": "4 2 ♭7 5 3 2",
            "udgs": "2 3 4 5 ♭7",
            "info": "",
            "strs": 6
        },
        "BDF♯AC♯E": {
            "name": "Bm11",
            "notes": "B D F♯ A C♯ E",
            "url_notes": "BDF%23AC%23E",
            "rev_notes": "E C♯ A F♯ D B",
            "dgs": "1 ♭3 5 ♭7 2 4",
            "rev_dgs": "4 2 ♭7 5 ♭3 1",
            "udgs": "1 2 ♭3 4 5 ♭7",
            "info": "",
            "strs": 6
        },
        "CGCEGC": {
            "name": "C",
            "notes": "C G C E G C",
            "url_notes": "CGCEGC",
            "rev_notes": "C G E C G C",
            "dgs": "1 5 1 3 5 1",
            "rev_dgs": "1 5 3 1 5 1",
            "udgs": "1 3 5",
            "info": "",
            "strs": 6
        },
        "CGCGCE": {
            "name": "C",
            "notes": "C G C G C E",
            "url_notes": "CGCGCE",
            "rev_notes": "E C G C G C",
            "dgs": "1 5 1 5 1 3",
            "rev_dgs": "3 1 5 1 5 1",
            "udgs": "1 3 5",
            "info": "",
            "strs": 6
        },
        "ACEGCE": {
            "name": "C6",
            "notes": "A C E G C E",
            "url_notes": "ACEGCE",
            "rev_notes": "E C G E C A",
            "dgs": "6 1 3 5 1 3",
            "rev_dgs": "3 1 5 3 1 6",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "CACGCE": {
            "name": "C6",
            "notes": "C A C G C E",
            "url_notes": "CACGCE",
            "rev_notes": "E C G C A C",
            "dgs": "1 6 1 5 1 3",
            "rev_dgs": "3 1 5 1 6 1",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "CEGACE": {
            "name": "C6",
            "notes": "C E G A C E",
            "url_notes": "CEGACE",
            "rev_notes": "E C A G E C",
            "dgs": "1 3 5 6 1 3",
            "rev_dgs": "3 1 6 5 3 1",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "CGCACE": {
            "name": "C6",
            "notes": "C G C A C E",
            "url_notes": "CGCACE",
            "rev_notes": "E C A C G C",
            "dgs": "1 5 1 6 1 3",
            "rev_dgs": "3 1 6 1 5 1",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "CGCGAE": {
            "name": "C6",
            "notes": "C G C G A E",
            "url_notes": "CGCGAE",
            "rev_notes": "E A G C G C",
            "dgs": "1 5 1 5 6 3",
            "rev_dgs": "3 6 5 1 5 1",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "ECGACE": {
            "name": "C6",
            "notes": "E C G A C E",
            "url_notes": "ECGACE",
            "rev_notes": "E C A G C E",
            "dgs": "3 1 5 6 1 3",
            "rev_dgs": "3 1 6 5 1 3",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "GCEACE": {
            "name": "C6",
            "notes": "G C E A C E",
            "url_notes": "GCEACE",
            "rev_notes": "E C A E C G",
            "dgs": "5 1 3 6 1 3",
            "rev_dgs": "3 1 6 3 1 5",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "GCEGAC": {
            "name": "C6",
            "notes": "G C E G A C",
            "url_notes": "GCEGAC",
            "rev_notes": "C A G E C G",
            "dgs": "5 1 3 5 6 1",
            "rev_dgs": "1 6 5 3 1 5",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "GCGACE": {
            "name": "C6",
            "notes": "G C G A C E",
            "url_notes": "GCGACE",
            "rev_notes": "E C A G C G",
            "dgs": "5 1 5 6 1 3",
            "rev_dgs": "3 1 6 5 1 5",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "CGCGA♯E": {
            "name": "C7",
            "notes": "C G C G A♯ E",
            "url_notes": "CGCGA%23E",
            "rev_notes": "E A♯ G C G C",
            "dgs": "1 5 1 5 ♭7 3",
            "rev_dgs": "3 ♭7 5 1 5 1",
            "udgs": "1 3 5 ♭7",
            "info": "",
            "strs": 6
        },
        "CEGA♯DE": {
            "name": "C9",
            "notes": "C E G A♯ D E",
            "url_notes": "CEGA%23DE",
            "rev_notes": "E D A♯ G E C",
            "dgs": "1 3 5 ♭7 2 3",
            "rev_dgs": "3 2 ♭7 5 3 1",
            "udgs": "1 3 5 2 ♭7",
            "info": "",
            "strs": 6
        },
        "GCEGA♯D": {
            "name": "C9",
            "notes": "G C E G A♯ D",
            "url_notes": "GCEGA%23D",
            "rev_notes": "D A♯ G E C G",
            "dgs": "5 1 3 5 ♭7 2",
            "rev_dgs": "2 ♭7 5 3 1 5",
            "udgs": "1 3 5 2 ♭7",
            "info": "",
            "strs": 6
        },
        "C♯EGA♯CD": {
            "name": "C9\/C♯",
            "notes": "C♯ E G A♯ C D",
            "url_notes": "C%23EGA%23CD",
            "rev_notes": "D C A♯ G E C♯",
            "dgs": "♭2 3 5 ♭7 1 2",
            "rev_dgs": "2 1 ♭7 5 3 ♭2",
            "udgs": "1 3 5 ♭2 2 ♭7",
            "info": "",
            "strs": 6
        },
        "A♯EGACE": {
            "name": "C13",
            "notes": "A♯ E G A C E",
            "url_notes": "A%23EGACE",
            "rev_notes": "E C A G E A♯",
            "dgs": "♭7 3 5 6 1 3",
            "rev_dgs": "3 1 6 5 3 ♭7",
            "udgs": "1 3 5 6 ♭7",
            "info": "",
            "strs": 6
        },
        "DADF♯AD": {
            "name": "D",
            "notes": "D A D F♯ A D",
            "url_notes": "DADF%23AD",
            "rev_notes": "D A F♯ D A D",
            "dgs": "1 5 1 3 5 1",
            "rev_dgs": "1 5 3 1 5 1",
            "udgs": "1 3 5",
            "info": "",
            "strs": 6
        },
        "fADF♯AD": {
            "name": "D\/Dm",
            "notes": "f A D F♯ A D",
            "url_notes": "fADF%23AD",
            "rev_notes": "D A F♯ D A f",
            "dgs": "♭3 5 1 3 5 1",
            "rev_dgs": "1 5 3 1 5 ♭3",
            "udgs": "1 3 5 ♭3",
            "info": "",
            "strs": 6
        },
        "DADDAD": {
            "name": "D5",
            "notes": "D A D D A D",
            "url_notes": "DADDAD",
            "rev_notes": "D A D D A D",
            "dgs": "1 5 1 1 5 1",
            "rev_dgs": "1 5 1 1 5 1",
            "udgs": "1 5",
            "info": "",
            "strs": 6
        },
        "ADF♯ABD": {
            "name": "D6",
            "notes": "A D F♯ A B D",
            "url_notes": "ADF%23ABD",
            "rev_notes": "D B A F♯ D A",
            "dgs": "5 1 3 5 6 1",
            "rev_dgs": "1 6 5 3 1 5",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "DADF♯BD": {
            "name": "D6",
            "notes": "D A D F♯ B D",
            "url_notes": "DADF%23BD",
            "rev_notes": "D B F♯ D A D",
            "dgs": "1 5 1 3 6 1",
            "rev_dgs": "1 6 3 1 5 1",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "DBDF♯AD": {
            "name": "D6",
            "notes": "D B D F♯ A D",
            "url_notes": "DBDF%23AD",
            "rev_notes": "D A F♯ D B D",
            "dgs": "1 6 1 3 5 1",
            "rev_dgs": "1 5 3 1 6 1",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "F♯BDF♯AD": {
            "name": "D6",
            "notes": "F♯ B D F♯ A D",
            "url_notes": "F%23BDF%23AD",
            "rev_notes": "D A F♯ D B F♯",
            "dgs": "3 6 1 3 5 1",
            "rev_dgs": "1 5 3 1 6 3",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "DACF♯AD": {
            "name": "D7",
            "notes": "D A C F♯ A D",
            "url_notes": "DACF%23AD",
            "rev_notes": "D A F♯ C A D",
            "dgs": "1 5 ♭7 3 5 1",
            "rev_dgs": "1 5 3 ♭7 5 1",
            "udgs": "1 3 5 ♭7",
            "info": "",
            "strs": 6
        },
        "DADF♯AC": {
            "name": "D7",
            "notes": "D A D F♯ A C",
            "url_notes": "DADF%23AC",
            "rev_notes": "C A F♯ D A D",
            "dgs": "1 5 1 3 5 ♭7",
            "rev_dgs": "♭7 5 3 1 5 1",
            "udgs": "1 3 5 ♭7",
            "info": "",
            "strs": 6
        },
        "DADF♯AC♯": {
            "name": "D7",
            "notes": "D A D F♯ A C♯",
            "url_notes": "DADF%23AC%23",
            "rev_notes": "C♯ A F♯ D A D",
            "dgs": "1 5 1 3 5 7",
            "rev_dgs": "7 5 3 1 5 1",
            "udgs": "1 3 5 7",
            "info": "",
            "strs": 6
        },
        "DADF♯CD": {
            "name": "D7",
            "notes": "D A D F♯ C D",
            "url_notes": "DADF%23CD",
            "rev_notes": "D C F♯ D A D",
            "dgs": "1 5 1 3 ♭7 1",
            "rev_dgs": "1 ♭7 3 1 5 1",
            "udgs": "1 3 5 ♭7",
            "info": "",
            "strs": 6
        },
        "DCDF♯AD": {
            "name": "D7",
            "notes": "D C D F♯ A D",
            "url_notes": "DCDF%23AD",
            "rev_notes": "D A F♯ D C D",
            "dgs": "1 ♭7 1 3 5 1",
            "rev_dgs": "1 5 3 1 ♭7 1",
            "udgs": "1 3 5 ♭7",
            "info": "",
            "strs": 6
        },
        "DADACD": {
            "name": "D7sus",
            "notes": "D A D A C D",
            "url_notes": "DADACD",
            "rev_notes": "D C A D A D",
            "dgs": "1 5 1 5 ♭7 1",
            "rev_dgs": "1 ♭7 5 1 5 1",
            "udgs": "1 5 ♭7",
            "info": "",
            "strs": 6
        },
        "ADF♯ACE": {
            "name": "D9",
            "notes": "A D F♯ A C E",
            "url_notes": "ADF%23ACE",
            "rev_notes": "E C A F♯ D A",
            "dgs": "5 1 3 5 ♭7 2",
            "rev_dgs": "2 ♭7 5 3 1 5",
            "udgs": "1 3 5 2 ♭7",
            "info": "",
            "strs": 6
        },
        "DEF♯ACE": {
            "name": "D9",
            "notes": "D E F♯ A C E",
            "url_notes": "DEF%23ACE",
            "rev_notes": "E C A F♯ E D",
            "dgs": "1 2 3 5 ♭7 2",
            "rev_dgs": "2 ♭7 5 3 2 1",
            "udgs": "1 3 5 2 ♭7",
            "info": "",
            "strs": 6
        },
        "DADACE": {
            "name": "D9sus",
            "notes": "D A D A C E",
            "url_notes": "DADACE",
            "rev_notes": "E C A D A D",
            "dgs": "1 5 1 5 ♭7 2",
            "rev_dgs": "2 ♭7 5 1 5 1",
            "udgs": "1 2 5 ♭7",
            "info": "",
            "strs": 6
        },
        "CDF♯ABD": {
            "name": "D13",
            "notes": "C D F♯ A B D",
            "url_notes": "CDF%23ABD",
            "rev_notes": "D B A F♯ D C",
            "dgs": "♭7 1 3 5 6 1",
            "rev_dgs": "1 6 5 3 1 ♭7",
            "udgs": "1 3 5 6 ♭7",
            "info": "",
            "strs": 6
        },
        "DADGAD": {
            "name": "Dsus4",
            "notes": "D A D G A D",
            "url_notes": "DADGAD",
            "rev_notes": "D A G D A D",
            "dgs": "1 5 1 4 5 1",
            "rev_dgs": "1 5 4 1 5 1",
            "udgs": "1 4 5",
            "info": "",
            "strs": 6
        },
        "DADFAD": {
            "name": "Dm",
            "notes": "D A D F A D",
            "url_notes": "DADFAD",
            "rev_notes": "D A F D A D",
            "dgs": "1 5 1 ♭3 5 1",
            "rev_dgs": "1 5 ♭3 1 5 1",
            "udgs": "1 ♭3 5",
            "info": "",
            "strs": 6
        },
        "EGDGBE": {
            "name": "D♯7",
            "notes": "E G D G B E",
            "url_notes": "EGDGBE",
            "rev_notes": "E B G D G E",
            "dgs": "2 4 1 4 6 2",
            "rev_dgs": "2 6 4 1 4 2",
            "udgs": "1 2 4 6",
            "info": "",
            "strs": 6
        },
        "EBEG♯BE": {
            "name": "E",
            "notes": "E B E G♯ B E",
            "url_notes": "EBEG%23BE",
            "rev_notes": "E B G♯ E B E",
            "dgs": "1 5 1 3 5 1",
            "rev_dgs": "1 5 3 1 5 1",
            "udgs": "1 3 5",
            "info": "",
            "strs": 6
        },
        "EBEG♯C♯E": {
            "name": "E6",
            "notes": "E B E G♯ C♯ E",
            "url_notes": "EBEG%23C%23E",
            "rev_notes": "E C♯ G♯ E B E",
            "dgs": "1 5 1 3 6 1",
            "rev_dgs": "1 6 3 1 5 1",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "G♯BEG♯C♯F♯": {
            "name": "E6\/9",
            "notes": "G♯ B E G♯ C♯ F♯",
            "url_notes": "G%23BEG%23C%23F%23",
            "rev_notes": "F♯ C♯ G♯ E B G♯",
            "dgs": "3 5 1 3 6 2",
            "rev_dgs": "2 6 3 1 5 3",
            "udgs": "1 3 5 2 6",
            "info": "",
            "strs": 6
        },
        "BDEG♯BE": {
            "name": "E7",
            "notes": "B D E G♯ B E",
            "url_notes": "BDEG%23BE",
            "rev_notes": "E B G♯ E D B",
            "dgs": "5 ♭7 1 3 5 1",
            "rev_dgs": "1 5 3 1 ♭7 5",
            "udgs": "1 3 5 ♭7",
            "info": "",
            "strs": 6
        },
        "EBEG♯BD": {
            "name": "E7",
            "notes": "E B E G♯ B D",
            "url_notes": "EBEG%23BD",
            "rev_notes": "D B G♯ E B E",
            "dgs": "1 5 1 3 5 ♭7",
            "rev_dgs": "♭7 5 3 1 5 1",
            "udgs": "1 3 5 ♭7",
            "info": "",
            "strs": 6
        },
        "EBEG♯BD♯": {
            "name": "E7",
            "notes": "E B E G♯ B D♯",
            "url_notes": "EBEG%23BD%23",
            "rev_notes": "D♯ B G♯ E B E",
            "dgs": "1 5 1 3 5 7",
            "rev_dgs": "7 5 3 1 5 1",
            "udgs": "1 3 5 7",
            "info": "",
            "strs": 6
        },
        "EDEG♯BE": {
            "name": "E7",
            "notes": "E D E G♯ B E",
            "url_notes": "EDEG%23BE",
            "rev_notes": "E B G♯ E D E",
            "dgs": "1 ♭7 1 3 5 1",
            "rev_dgs": "1 5 3 1 ♭7 1",
            "udgs": "1 3 5 ♭7",
            "info": "",
            "strs": 6
        },
        "EEG♯BDE": {
            "name": "E7",
            "notes": "E E G♯ B D E",
            "url_notes": "EEG%23BDE",
            "rev_notes": "E D B G♯ E E",
            "dgs": "1 1 3 5 ♭7 1",
            "rev_dgs": "1 ♭7 5 3 1 1",
            "udgs": "1 3 5 ♭7",
            "info": "",
            "strs": 6
        },
        "BDF♯G♯BE": {
            "name": "E9",
            "notes": "B D F♯ G♯ B E",
            "url_notes": "BDF%23G%23BE",
            "rev_notes": "E B G♯ F♯ D B",
            "dgs": "5 ♭7 2 3 5 1",
            "rev_dgs": "1 5 3 2 ♭7 5",
            "udgs": "1 3 5 2 ♭7",
            "info": "",
            "strs": 6
        },
        "DEF♯G♯BE": {
            "name": "E9",
            "notes": "D E F♯ G♯ B E",
            "url_notes": "DEF%23G%23BE",
            "rev_notes": "E B G♯ F♯ E D",
            "dgs": "♭7 1 2 3 5 1",
            "rev_dgs": "1 5 3 2 1 ♭7",
            "udgs": "1 3 5 2 ♭7",
            "info": "",
            "strs": 6
        },
        "G♯BEG♯DF♯": {
            "name": "E9",
            "notes": "G♯ B E G♯ D F♯",
            "url_notes": "G%23BEG%23DF%23",
            "rev_notes": "F♯ D G♯ E B G♯",
            "dgs": "3 5 1 3 ♭7 2",
            "rev_dgs": "2 ♭7 3 1 5 3",
            "udgs": "1 3 5 2 ♭7",
            "info": "",
            "strs": 6
        },
        "BDEG♯C♯E": {
            "name": "E13",
            "notes": "B D E G♯ C♯ E",
            "url_notes": "BDEG%23C%23E",
            "rev_notes": "E C♯ G♯ E D B",
            "dgs": "5 ♭7 1 3 6 1",
            "rev_dgs": "1 6 3 1 ♭7 5",
            "udgs": "1 3 5 6 ♭7",
            "info": "",
            "strs": 6
        },
        "FCFACF": {
            "name": "F",
            "notes": "F C F A C F",
            "url_notes": "FCFACF",
            "rev_notes": "F C A F C F",
            "dgs": "1 5 1 3 5 1",
            "rev_dgs": "1 5 3 1 5 1",
            "udgs": "1 3 5",
            "info": "",
            "strs": 6
        },
        "FAFACE": {
            "name": "F7",
            "notes": "F A F A C E",
            "url_notes": "FAFACE",
            "rev_notes": "E C A F A F",
            "dgs": "1 3 1 3 5 7",
            "rev_dgs": "7 5 3 1 3 1",
            "udgs": "1 3 5 7",
            "info": "",
            "strs": 6
        },
        "FCFACE": {
            "name": "F7",
            "notes": "F C F A C E",
            "url_notes": "FCFACE",
            "rev_notes": "E C A F C F",
            "dgs": "1 5 1 3 5 7",
            "rev_dgs": "7 5 3 1 5 1",
            "udgs": "1 3 5 7",
            "info": "",
            "strs": 6
        },
        "F♯A♯EG♯C♯E": {
            "name": "F#9",
            "notes": "F♯ A♯ E G♯ C♯ E",
            "url_notes": "F%23A%23EG%23C%23E",
            "rev_notes": "E C♯ G♯ E A♯ F♯",
            "dgs": "♭2 4 7 ♭3 ♭6 7",
            "rev_dgs": "7 ♭6 ♭3 7 4 ♭2",
            "udgs": "♭2 ♭3 4 ♭6 7",
            "info": "",
            "strs": 6
        },
        "DGDGBD": {
            "name": "Open G",
            "notes": "D G D G B D",
            "url_notes": "DGDGBD",
            "rev_notes": "D B G D G D",
            "dgs": "5 1 5 1 3 5",
            "rev_dgs": "5 3 1 5 1 5",
            "udgs": "1 3 5",
            "info": "Keith Richards / blues",
            "strs": 6
        },
        "GBDGBD": {
            "name": "G-Dobro",
            "notes": "G B D G B D",
            "url_notes": "GBDGBD",
            "rev_notes": "D B G D B G",
            "dgs": "1 3 5 1 3 5",
            "rev_dgs": "5 3 1 5 3 1",
            "udgs": "1 3 5",
            "info": "",
            "strs": 6
        },
        "BDEGBD": {
            "name": "G6",
            "notes": "B D E G B D",
            "url_notes": "BDEGBD",
            "rev_notes": "D B G E D B",
            "dgs": "3 5 6 1 3 5",
            "rev_dgs": "5 3 1 6 5 3",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "DGEGBD": {
            "name": "G6",
            "notes": "D G E G B D",
            "url_notes": "DGEGBD",
            "rev_notes": "D B G E G D",
            "dgs": "5 1 6 1 3 5",
            "rev_dgs": "5 3 1 6 1 5",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "EBDGBD": {
            "name": "G6",
            "notes": "E B D G B D",
            "url_notes": "EBDGBD",
            "rev_notes": "D B G D B E",
            "dgs": "6 3 5 1 3 5",
            "rev_dgs": "5 3 1 5 3 6",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "EGBGBD": {
            "name": "G6",
            "notes": "E G B G B D",
            "url_notes": "EGBGBD",
            "rev_notes": "D B G B G E",
            "dgs": "6 1 3 1 3 5",
            "rev_dgs": "5 3 1 3 1 6",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "EGDGBD": {
            "name": "G6",
            "notes": "E G D G B D",
            "url_notes": "EGDGBD",
            "rev_notes": "D B G D G E",
            "dgs": "6 1 5 1 3 5",
            "rev_dgs": "5 3 1 5 1 6",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "GBDEGB": {
            "name": "G6",
            "notes": "G B D E G B",
            "url_notes": "GBDEGB",
            "rev_notes": "B G E D B G",
            "dgs": "1 3 5 6 1 3",
            "rev_dgs": "3 1 6 5 3 1",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "GBEGBD": {
            "name": "G6",
            "notes": "G B E G B D",
            "url_notes": "GBEGBD",
            "rev_notes": "D B G E B G",
            "dgs": "1 3 6 1 3 5",
            "rev_dgs": "5 3 1 6 3 1",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "GDEGBD": {
            "name": "G6",
            "notes": "G D E G B D",
            "url_notes": "GDEGBD",
            "rev_notes": "D B G E D G",
            "dgs": "1 5 6 1 3 5",
            "rev_dgs": "5 3 1 6 5 1",
            "udgs": "1 3 5 6",
            "info": "",
            "strs": 6
        },
        "GBDFGD": {
            "name": "G7",
            "notes": "G B D F G D",
            "url_notes": "GBDFGD",
            "rev_notes": "D G F D B G",
            "dgs": "1 3 5 ♭7 1 5",
            "rev_dgs": "5 1 ♭7 5 3 1",
            "udgs": "1 3 5 ♭7",
            "info": "",
            "strs": 6
        },
        "GBDF♯BD": {
            "name": "G7",
            "notes": "G B D F♯ B D",
            "url_notes": "GBDF%23BD",
            "rev_notes": "D B F♯ D B G",
            "dgs": "1 3 5 7 3 5",
            "rev_dgs": "5 3 7 5 3 1",
            "udgs": "1 3 5 7",
            "info": "",
            "strs": 6
        },
        "GBDFAD": {
            "name": "G9",
            "notes": "G B D F A D",
            "url_notes": "GBDFAD",
            "rev_notes": "D A F D B G",
            "dgs": "1 3 5 ♭7 2 5",
            "rev_dgs": "5 2 ♭7 5 3 1",
            "udgs": "1 3 5 2 ♭7",
            "info": "",
            "strs": 6
        },
        "GBDFAC": {
            "name": "G11",
            "notes": "G B D F A C",
            "url_notes": "GBDFAC",
            "rev_notes": "C A F D B G",
            "dgs": "1 3 5 ♭7 2 4",
            "rev_dgs": "4 2 ♭7 5 3 1",
            "udgs": "1 3 5 2 4 ♭7",
            "info": "",
            "strs": 6
        },
        "CEGBDF": {
            "name": "G13",
            "notes": "C E G B D F",
            "url_notes": "CEGBDF",
            "rev_notes": "F D B G E C",
            "dgs": "4 6 1 3 5 ♭7",
            "rev_dgs": "♭7 5 3 1 6 4",
            "udgs": "1 3 5 4 6 ♭7",
            "info": "",
            "strs": 6
        },
        "EGBGDF": {
            "name": "G13",
            "notes": "E G B G D F",
            "url_notes": "EGBGDF",
            "rev_notes": "F D G B G E",
            "dgs": "6 1 3 1 5 ♭7",
            "rev_dgs": "♭7 5 1 3 1 6",
            "udgs": "1 3 5 6 ♭7",
            "info": "",
            "strs": 6
        },
        "GBDGA♯D": {
            "name": "Gm\/G",
            "notes": "G B D G A♯ D",
            "url_notes": "GBDGA%23D",
            "rev_notes": "D A♯ G D B G",
            "dgs": "1 3 5 1 ♭3 5",
            "rev_dgs": "5 ♭3 1 5 3 1",
            "udgs": "1 3 5 ♭3",
            "info": "",
            "strs": 6
        },
        "GA♯DFAC": {
            "name": "Gm11",
            "notes": "G A♯ D F A C",
            "url_notes": "GA%23DFAC",
            "rev_notes": "C A F D A♯ G",
            "dgs": "1 ♭3 5 ♭7 2 4",
            "rev_dgs": "4 2 ♭7 5 ♭3 1",
            "udgs": "1 2 ♭3 4 5 ♭7",
            "info": "",
            "strs": 6
        },
        "GBDF♯AD": {
            "name": "Gmaj9-Hybrid",
            "notes": "G B D F♯ A D",
            "url_notes": "GBDF%23AD",
            "rev_notes": "D A F♯ D B G",
            "dgs": "1 3 5 7 2 5",
            "rev_dgs": "5 2 7 5 3 1",
            "udgs": "1 3 5 2 7",
            "info": "",
            "strs": 6
        },
        "ADF♯AC♯EF♯AC♯E": {
            "name": "A6",
            "notes": "A D F♯ A C♯ E F♯ A C♯ E",
            "url_notes": "ADF%23AC%23EF%23AC%23E",
            "rev_notes": "E C♯ A F♯ E C♯ A F♯ D A",
            "dgs": "1 4 6 1 3 5 6 1 3 5",
            "rev_dgs": "5 3 1 6 5 3 1 6 4 1",
            "udgs": "1 3 4 5 6",
            "info": "",
            "strs": 10
        },
        "BDEF♯G♯BC♯EG♯F♯": {
            "name": "E6",
            "notes": "B D E F♯ G♯ B C♯ E G♯ F♯",
            "url_notes": "BDEF%23G%23BC%23EG%23F%23",
            "rev_notes": "F♯ G♯ E C♯ B G♯ F♯ E D B",
            "dgs": "5 ♭7 1 2 3 5 6 1 3 2",
            "rev_dgs": "2 3 1 6 5 3 2 1 ♭7 5",
            "udgs": "1 2 3 5 6 ♭7",
            "info": "",
            "strs": 10
        },
        "CFACEGACEG": {
            "name": "C6\/Fmaj9",
            "notes": "C F A C E G A C E G",
            "url_notes": "CFACEGACEG",
            "rev_notes": "G E C A G E C A F C",
            "dgs": "1 4 6 1 3 5 6 1 3 5",
            "rev_dgs": "5 3 1 6 5 3 1 6 4 1",
            "udgs": "1 3 4 5 6",
            "info": "",
            "strs": 10
        },
        "C♯EFF♯GG♯ABC♯E": {
            "name": "E Harp",
            "notes": "C♯ E F F♯ G G♯ A B C♯ E",
            "url_notes": "C%23EFF%23GG%23ABC%23E",
            "rev_notes": "E C♯ B A G♯ G F♯ F E C♯",
            "dgs": "6 1 ♭2 2 ♭3 3 4 5 6 1",
            "rev_dgs": "1 6 5 4 3 ♭3 2 ♭2 1 6",
            "udgs": "1 ♭2 2 ♭3 3 4 5 6",
            "info": "Eddie Alkire",
            "strs": 10
        },
        "EDEF♯G♯BC♯EF♯G♯": {
            "name": "E13",
            "notes": "E D E F♯ G♯ B C♯ E F♯ G♯",
            "url_notes": "EDEF%23G%23BC%23EF%23G%23",
            "rev_notes": "G♯ F♯ E C♯ B G♯ F♯ E D E",
            "dgs": "1 ♭7 1 2 3 5 6 1 2 3",
            "rev_dgs": "3 2 1 6 5 3 2 1 ♭7 1",
            "udgs": "1 2 3 5 6 ♭7",
            "info": "Eddie Alkire",
            "strs": 10
        },
        "EG♯BDEG♯BDEG♯": {
            "name": "E7",
            "notes": "E G♯ B D E G♯ B D E G♯",
            "url_notes": "EG%23BDEG%23BDEG%23",
            "rev_notes": "G♯ E D B G♯ E D B G♯ E",
            "dgs": "1 3 5 ♭7 1 3 5 ♭7 1 3",
            "rev_dgs": "3 1 ♭7 5 3 1 ♭7 5 3 1",
            "udgs": "1 3 5 ♭7",
            "info": "",
            "strs": 10
        },
        "FACEGACEGD": {
            "name": "C6",
            "notes": "F A C E G A C E G D",
            "url_notes": "FACEGACEGD",
            "rev_notes": "D G E C A G E C A F",
            "dgs": "4 6 1 3 5 6 1 3 5 2",
            "rev_dgs": "2 5 3 1 6 5 3 1 6 4",
            "udgs": "1 2 3 4 5 6",
            "info": "Robinson\/Pedal Steel",
            "strs": 10
        },
        "BEG♯BEF♯G♯BEG♯D♯F♯": {
            "name": "E9",
            "notes": "B E G♯ B E F♯ G♯ B E G♯ D♯ F♯",
            "url_notes": "BEG%23BEF%23G%23BEG%23D%23F%23",
            "rev_notes": "F♯ D♯ G♯ E B G♯ F♯ E B G♯ E B",
            "dgs": "5 1 3 5 1 2 3 5 1 3 7 2",
            "rev_dgs": "2 7 3 1 5 3 2 1 5 3 1 5",
            "udgs": "1 2 3 5 7",
            "info": "",
            "strs": 12
        },
        "DFACEGACEGBD": {
            "name": "C6th\/G13",
            "notes": "D F A C E G A C E G B D",
            "url_notes": "DFACEGACEGBD",
            "rev_notes": "D B G E C A G E C A F D",
            "dgs": "2 4 6 1 3 5 6 1 3 5 7 2",
            "rev_dgs": "2 7 5 3 1 6 5 3 1 6 4 2",
            "udgs": "1 2 3 4 5 6 7",
            "info": "Bobby Black\/Reese Anderson",
            "strs": 12
        },
        "DADF♯AD": {
            "name": "Open D",
            "notes": "D A D F♯ A D",
            "url_notes": "DADFsAD",
            "rev_notes": "D A F♯ D A D",
            "dgs": "1 5 1 3 5 1",
            "rev_dgs": "1 5 3 1 5 1",
            "udgs": "1 3 5",
            "info": "Joni Mitchell / blues",
            "strs": 6
        },
        "EAEAC♯E": {
            "name": "Open A",
            "notes": "E A E A C♯ E",
            "url_notes": "EAEACsE",
            "rev_notes": "E C♯ A E A E",
            "dgs": "5 1 5 1 3 5",
            "rev_dgs": "5 3 1 5 1 5",
            "udgs": "1 3 5",
            "info": "Open G shape, whole step up",
            "strs": 6
        },
        "DADGBE": {
            "name": "Drop D",
            "notes": "D A D G B E",
            "url_notes": "DADGBE",
            "rev_notes": "E B G D A D",
            "dgs": "1 5 1 4 6 2",
            "rev_dgs": "2 6 4 1 5 1",
            "udgs": "1 2 4 5 6",
            "info": "standard guitar, low E dropped to D",
            "strs": 6
        },
        "EBEG♯BE": {
            "name": "Open E",
            "notes": "E B E G♯ B E",
            "url_notes": "EBEGsBE",
            "rev_notes": "E B G♯ E B E",
            "dgs": "1 5 1 3 5 1",
            "rev_dgs": "1 5 3 1 5 1",
            "udgs": "1 3 5",
            "info": "Duane Allman / slide guitar",
            "strs": 6
        },
        "EADG": {
            "name": "Bass",
            "notes": "E A D G",
            "url_notes": "EADG",
            "rev_notes": "G D A E",
            "dgs": "1 4 ♭7 ♭3",
            "rev_dgs": "♭3 ♭7 4 1",
            "udgs": "1 ♭3 4 ♭7",
            "info": "4-string bass, standard tuning",
            "strs": 4
        },
        "GCEA": {
            "name": "Ukulele",
            "notes": "G C E A",
            "url_notes": "GCEA",
            "rev_notes": "A E C G",
            "dgs": "1 4 6 2",
            "rev_dgs": "2 6 4 1",
            "udgs": "1 2 4 6",
            "info": "Soprano / concert / tenor ukulele (reentrant high G)",
            "strs": 4
        },
        "GDGBD": {
            "name": "Banjo Open G",
            "notes": "G D G B D",
            "url_notes": "GDGBD",
            "rev_notes": "D B G D G",
            "dgs": "1 5 1 3 5",
            "rev_dgs": "5 3 1 5 1",
            "udgs": "1 3 5",
            "info": "5-string banjo, 5th string high G drone",
            "strs": 5
        }
    }
};

window.SF_GRID_ROWS = [{"degId":"_7_","intervalLabel":"(14)","cells":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]},{"degId":"_b7_","intervalLabel":"(♭14)","cells":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]},{"degId":"_6_","intervalLabel":"(13)","cells":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"13","13","13",null,null,"13",null,null]},{"degId":"_b6_","intervalLabel":"(♭13)","cells":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"♭13",null,null,null]},{"degId":"_5_","intervalLabel":"(12)","cells":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]},{"degId":"_b5_","intervalLabel":"(♭12)","cells":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"♭12",null,null,null,null,null,null,null,null]},{"degId":"_4_","intervalLabel":"(11)","cells":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"11","11",null,"11","11","11",null,null,null,null,null]},{"degId":"_3_","intervalLabel":"(10)","cells":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]},{"degId":"_b3_","intervalLabel":"(♭10)","cells":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"♭10",null,null,null,null,null,null,null,null,null,null,null]},{"degId":"_2_","intervalLabel":"(9)","cells":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"9","9","9","9",null,"9",null,"9","9","9","9","9","9","9",null,null,null,null]},{"degId":"_b2_","intervalLabel":"(♭9)","cells":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"♭9",null,null,null,null,null,null,null,null,null,null,"♭9",null,null]},{"degId":"_1_","intervalLabel":"(8)","cells":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]},{"degId":"_7_","intervalLabel":"(7)","cells":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,"7","7",null,null,null,null,null,"7",null,null,null,null,null,null,"7","7",null,null,null,null]},{"degId":"_b7_","intervalLabel":"(♭7)","cells":[null,null,null,null,null,null,null,null,"♭7","♭7","♭7","♭7",null,"♭7",null,null,null,null,null,"♭7","♭7",null,"♭7","♭7","♭7","♭7","♭7","♭7",null,null,"♭7","♭7",null,null]},{"degId":"_6_","intervalLabel":"(6)","cells":[null,null,null,null,null,null,"6","6",null,null,null,null,"6",null,null,null,null,null,"6",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]},{"degId":"_b6_","intervalLabel":"(♭6)","cells":[null,null,"♭6",null,null,null,null,null,null,null,"♭6",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]},{"degId":"_5_","intervalLabel":"(5)","cells":["5","5",null,null,"5","5","5","5","5","5",null,null,null,null,"5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5"]},{"degId":"_b5_","intervalLabel":"(♭5)","cells":[null,null,null,"♭5",null,null,null,null,null,null,null,"♭5","♭5","♭5",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]},{"degId":"_4_","intervalLabel":"(4)","cells":[null,null,null,null,null,"4",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"4","4"]},{"degId":"_3_","intervalLabel":"(3)","cells":["3",null,"3",null,null,null,"3",null,"3",null,"3","3",null,null,"3",null,"3",null,"3","3","3","3","3","3",null,"3","3",null,"3",null,"3","3",null,"3"]},{"degId":"_b3_","intervalLabel":"(♭3)","cells":[null,"♭3",null,"♭3",null,null,null,"♭3",null,"♭3",null,null,"♭3","♭3",null,"♭3",null,"♭3",null,null,null,null,null,null,"♭3",null,null,"♭3",null,"♭3",null,null,null,null]},{"degId":"_2_","intervalLabel":"(2)","cells":[null,null,null,null,"2",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"2",null]},{"degId":"_b2_","intervalLabel":"(♭2)","cells":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]},{"degId":"_1_","intervalLabel":"(1)","cells":["1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1"]}];
