// Per-section help text for the ? About buttons. Pure static strings,
// extracted from js/app.js so the main renderer file stays focused on
// behaviour. Loaded as a global before app.js (see index.html script
// order); app.js reads `window.SF_HELP` into its local SECTION_HELP.
window.SF_HELP = {
  about: [
    '',
    '  ███████ ██████  ███████ ████████ ██████   ██████   █████  ██████  ██████',
    '  ██      ██   ██ ██         ██    ██   ██ ██    ██ ██   ██ ██   ██ ██   ██',
    '  █████   ██████  █████      ██    ██████  ██    ██ ███████ ██████  ██   ██',
    '  ██      ██   ██ ██         ██    ██   ██ ██    ██ ██   ██ ██  ██  ██   ██',
    '  ██      ██   ██ ███████    ██    ██████   ██████  ██   ██ ██   ██ ██████  .site',
    '',
    '  About Fretboard.site',
    '  ====================',
    '',
    '  A free, in-browser music-theory playground. No signup, no server-',
    '  side state — every selection you make lives in the URL, so copy the',
    '  address bar and you have a shareable, bookmark-able view.',
    '',
    '  What is on the page (top → bottom; sections can be reordered by',
    '  dragging the handle on the left edge of each title bar):',
    '',
    '    • FRETBOARD — the main tool. Pick a tuning + key, highlight a',
    '      chord or scale, see every position across the neck. Supports',
    '      4- to 12-string instruments across 176 preset tunings plus a',
    '      custom builder. Click any fret to pick notes for Chord ID.',
    '    • PROGRESSIONS — type Roman numerals or chord names, hit play.',
    '    • CHORD BUILDER GRID — 28+ chord types in any key, laid out by',
    '      interval. Click a row to highlight it everywhere else.',
    '    • SCALE BUILDER GRID — 16 scales (modes, pentatonic, blues,',
    '      harmonic / melodic minor, …) in any key.',
    '    • KEY SIGNATURES — every major key with its treble-clef staff,',
    '      sharps/flats count, hand-signal mnemonic, and an interactive',
    '      Circle of Fifths.',
    '    • KEYBOARD — full 88-key piano view (A0 → C8) with note names,',
    '      frequencies, instrument ranges, and 10-band EQ bands.',
    '    • QUIZ — endless randomly-generated music-theory practice.',
    '    • TAB — in-page tab editor with chord-box diagrams, print-ready.',
    '    • SHEET MUSIC — searchable progressions from a 4,000+ fake-book',
    '      library (in progress).',
    '    • EAR TRAINING — interval and chord-identification drills.',
    '    • FRETBOARD #2 / KEYBOARD #2 — second instances for A/B',
    '      comparison. Unlock 🔒 to give each its own key / tuning.',
    '',
    '  Site-wide controls (sticky header, always visible):',
    '    • Display mode — show note names, degrees, or both.',
    '    • KEY buttons — twelve A–G♯ pills; picks apply page-wide.',
    '    • Tips — toggle hover tooltips across the whole site.',
    '    • ♪ Audio — turn on the synth so clicks play.',
    '    • Instrument — pick which Tone.js voice plays.',
    '    • Clear — wipe every URL parameter and reset to defaults.',
    '',
    '  Every section has its own ? for in-depth help. Hover any control',
    '  with Tips on for a short description of what it does.',
    ''
  ].join('\n'),

  fretboard: [
    '',
    '  ███████ ██████  ███████ ████████ ██████   ██████   █████  ██████  ██████',
    '  ██      ██   ██ ██         ██    ██   ██ ██    ██ ██   ██ ██   ██ ██   ██',
    '  █████   ██████  █████      ██    ██████  ██    ██ ███████ ██████  ██   ██',
    '  ██      ██   ██ ██         ██    ██   ██ ██    ██ ██   ██ ██  ██  ██   ██',
    '  ██      ██   ██ ███████    ██    ██████   ██████  ██   ██ ██   ██ ██████  .site',
    '',
    '  Fretboard',
    '  =========',
    '',
    '  An interactive fretboard for 4- to 12-string instruments — guitar,',
    '  bass, ukulele, banjo, mandolin, lap steel, pedal steel, and anything',
    '  in between. Each row is a string; columns 0–12 are frets. Each cell',
    '  shows the note name and its scale degree relative to the current Key.',
    '',
    '  Reading the board:',
    '    • Column 0 (left of the thick light-coloured nut) is the open',
    '      string — the pitch when no fret is held down.',
    '    • The thick vertical bar between fret 0 and fret 1 is the NUT.',
    '    • Cells are coloured by the chord/scale you have highlighted —',
    '      every "1" is one shade, every "♭3" is another, etc.',
    '',
    '  Controls in this section:',
    '    • TUNING picker (top-left) — click to open a sortable / filterable',
    '      table of 176 preset tunings. The number of strings + the preset',
    '      drive what each row shows.',
    '    • CUSTOM tab (inside the tuning picker) — switch to Custom to',
    '      build your own tuning string by string; the tuning picker',
    '      saves it and uses it until you pick a different preset.',
    '    • LH / RH — mirror the fretboard horizontally for left-handed',
    '      play (the nut moves to the right, fret 12 to the left).',
    '    • L→H / H→L — flips the string order (high pitch on top vs.',
    '      bottom). Personal preference.',
    '    • DEGREE / NOTE PILLS — twelve stacked buttons across the top, one',
    '      per chromatic step. Click any pill to add or remove that degree',
    '      from the highlight set. "All" turns every pill on; "None" drops',
    '      just the colored highlights (chord-ID picks stay).',
    '    • CHORD / SCALE / KEY-SET CHIPS — quick-pick rows of common chord',
    '      shapes, common scales, and one-click "set to this key" buttons.',
    '',
    '  Sticky header (top of page):',
    '    • LOGO — center, click to reset the URL.',
    '    • TUNING — left, current tuning + notes + degrees.',
    '    • KEY — center row, twelve A–G♯ buttons. Picks apply page-wide.',
    '    • Audio (♪) — right, turn on a small synth so cell / chip / chord',
    '      clicks play.',
    '    • Clear — right, wipes every highlight AND every chord-ID pick.',
    '',
    '  Click-to-pick lives in the Chord ID sub-section (below the board).',
    '',
    '  Bookmark / share: every selection (tuning, key, custom strings,',
    '  highlights, picks, collapsed sections, sort, filter, progression)',
    '  lives in the URL. Copy the address bar and you have a shareable view.',
    ''
  ].join('\n'),

  chord_id: [
    '',
    '  Chord ID',
    '  ========',
    '',
    '  Tells you what chord(s) the currently HIGHLIGHTED notes form.',
    '  Anything that adds a note to the color-highlight set feeds it:',
    '',
    '    • Note buttons in the fretboard/keyboard summary row.',
    '    • Clicking a fret cell or a piano key (toggles that note).',
    '    • Chord & Scale Picks chips (one-shot replace).',
    '    • Chord/Scale builder grid rows.',
    '',
    '  Once 3 or more notes are highlighted, suggestion chips appear',
    '  in three buckets:',
    '    EXACT — chords whose notes exactly match the highlights.',
    '    CONTAINS — chords that fit inside the highlights (you have',
    '               extras, but those notes are a chord by themselves).',
    '    COULD BE (+ extras) — chords the highlights are PART of; the',
    '               +1 / +2 / +All toggle controls how many extra',
    '               notes are allowed.',
    '',
    '  Hover any chip to outline that chord\'s notes on the fretboard /',
    '  keyboard — a live preview of what the chord looks like without',
    '  touching your current highlights. If you want the chord engaged,',
    '  click those notes directly on the board.',
    '',
    '  Filters:',
    '    • IN KEY pill — narrows suggestions to chords whose ROOT',
    '      matches the current key.',
    '    • +1 / +2 / +All — caps the "could be" bucket\'s extras count.',
    '',
    '  Above the strip:',
    '    • ◀ / ▶ shift bar — bumps the site key ±1 semitone, sliding',
    '      every highlight up/down the neck.',
    '    • Clear (right side of the strip) — drops every highlight.',
    ''
  ].join('\n'),

  chord_grid: [
    '',
    '  Chord Builder Grid',
    '  ==================',
    '',
    '  A grid of 28+ chord types (Maj, Min, 7, m7, Maj7, dim, dim7, aug,',
    '  sus2, sus4, 6, m6, 9, m9, Maj9, 11, 13, add9, …) showing which',
    '  scale degrees make up each chord.',
    '',
    '  How to read it:',
    '    • Each ROW is one chord type. The label on either end shows the',
    '      chord name and its degree formula (e.g. "Maj7  1-3-5-7").',
    '    • Each COLUMN is a scale degree (1 / ♭2 / 2 / ♭3 / 3 / 4 / ♭5 /',
    '      5 / ♭6 / 6 / ♭7 / 7). The header shows the actual note name in',
    '      the current key.',
    '    • A filled cell means that degree IS part of that chord. Cells',
    '      are coloured by their degree.',
    '    • Click ANYWHERE on a row to highlight that chord across the',
    '      fretboard and keyboard — every position lights up.',
    '',
    '  Above the grid:',
    '    • DIATONIC CHORDS — the 7 chords built on each note of the',
    '      current major scale (I, ii, iii, IV, V, vi, vii°). Coloured',
    '      by harmonic function: tonic / subdominant / dominant. Toggle',
    '      between triads and 7th chords with the pill on the right.',
    '    • INVERSIONS — when a chord is highlighted, this panel shows',
    '      the chord rotated so each chord tone sits in the bass.',
    '      "Root position" puts the chord\'s own root in the bass; 1st',
    '      inversion puts the 3rd in the bass; 2nd puts the 5th there.',
    '',
    '  Below: PROGRESSIONS — common chord progressions in the current',
    '  key with audio playback (Audio pill must be on).',
    '',
    '  Use the KEY picker or click a different cell to change context.',
    '  Hover any cell for a tooltip with degrees, notes, and which scales',
    '  contain that chord.',
    ''
  ].join('\n'),

  scale_grid: [
    '',
    '  Scale Builder Grid',
    '  ==================',
    '',
    '  Every common scale, laid out by degree.',
    '',
    '  Scales included:',
    '    • The 7 modes of major: Ionian, Dorian, Phrygian, Lydian,',
    '      Mixolydian, Aeolian (natural minor), Locrian',
    '    • Melodic Minor, Harmonic Minor',
    '    • Phrygian Dominant, Hungarian Minor',
    '    • Major Pentatonic, Minor Pentatonic, Blues',
    '    • Whole Tone, Diminished',
    '',
    '  How to read it:',
    '    • Each ROW is one scale. The label shows scale name and degree',
    '      formula (e.g. "Dorian  1-2-♭3-4-5-6-♭7"). Hover for the W-H',
    '      step pattern (W = whole step, H = half step).',
    '    • Each COLUMN is a degree. A filled cell means that degree',
    '      belongs to that scale.',
    '    • Click ANYWHERE on a row to highlight that scale across the',
    '      fretboard and keyboard.',
    '',
    '  Above the grid: MODES — all 7 modes derived from the current key',
    '  shown side-by-side. They share the same notes; only the tonal',
    '  centre changes. Each mode\'s "interval signature" tells you how it',
    '  differs from major (e.g. Dorian = ♭3 ♭7).',
    '',
    '  Notation note: scales that classically include ♯4, ♯5, or ♯6',
    '  display the enharmonic equivalents ♭5, ♭6, ♭7 because the site\'s',
    '  12-tone alphabet has only one slot per pitch class.',
    ''
  ].join('\n'),

  keyboard: [
    '',
    '  Keyboard',
    '  ========',
    '',
    '  An 88-key piano view from A0 to C8. The same key + highlight state',
    '  drives this section as the fretboard, so anything you select on one',
    '  shows up on the other.',
    '',
    '  Each note also has reference data labelled on the row above:',
    '    • OCTAVE NUMBER (0–8)',
    '    • STEEL STRING GAUGE that targets that pitch (.072 down to .011)',
    '    • 10-BAND EQ frequency centre that note falls into',
    '    • FREQUENCY in Hz',
    '    • INSTRUMENT RANGE bands for guitar and bass',
    '',
    '  How highlights work:',
    '    By default keys read as a real piano (white keys white, black',
    '    keys dark). When you highlight one or more degrees, the matching',
    '    notes pick up the degree colour — every other note stays plain',
    '    so your selection pops. Highlight every degree to see the full',
    '    rainbow.',
    '',
    '  Above the keyboard:',
    '    • DEGREE / NOTE PILLS — twelve stacked buttons, one per chromatic',
    '      step. Click to add or remove that degree from the highlight set.',
    '      "All" turns every pill on; "None" drops just the colored',
    '      highlights (chord-ID picks stay).',
    '',
    '  Click-to-pick lives in the Chord ID sub-section below the keyboard.',
    '  Click keys with Chord ID toggled on, and the strip names every',
    '  chord your picks form. See the Chord ID help (?) for details.',
    ''
  ].join('\n'),

  tunings: [
    '',
    '  Tunings List',
    '  ============',
    '',
    '  176 preset tunings — standard and drop tunings for guitar and bass,',
    '  ukulele variations, banjo open tunings, mandolin, plus the steel-',
    '  guitar staples (lap A6 / C6 / E13, pedal E9 / B6 / C6 / Universal).',
    '',
    '  How to use:',
    '    • Click any COLUMN HEADER to sort. Click again to reverse direction.',
    '    • Use the FILTER input to narrow the list — matches across name,',
    '      notes, degrees, info, and string count.',
    '    • Use the STRING-COUNT BUTTONS to pin a specific count. They\'re',
    '      toggles, so clicking the same one again clears the filter.',
    '    • Click ANYWHERE on a row to load that tuning into the fretboard.',
    '      The current Key and highlights stay put.',
    '    • Hit CSV in the section header to download the currently visible',
    '      (sorted + filtered) tunings as a comma-separated file.',
    '',
    '  Sort, filter, and the chosen tuning all live in the URL, so a',
    '  filtered view is bookmarkable / shareable.',
    ''
  ].join('\n'),

  progressions: [
    '',
    '  Progressions',
    '  ============',
    '',
    '  A chord progression builder. Type chords, pick from the palette,',
    '  or hit the + add-box; mix Roman numerals (transpose with the key)',
    '  with absolute chord names (stay put) freely.',
    '',
    '  Top row (centered):',
    '    • CHORD PROGRESSION input — type the progression, e.g.',
    '         "I IV V"          (Romans, transpose with the key)',
    '         "C Am F G"        (absolute chords, stay put)',
    '         "Cmaj7 Dm7 G7"    (with voicings)',
    '       Press SPACE or ENTER to apply. Tokens auto-apply as you type.',
    '       The Roman regex accepts ♭ / ♯ prefixes, lowercase = minor,',
    '       and a trailing ° for diminished or 7 for sevenths.',
    '    • ♯ / ♭ buttons — click to insert the proper accidental glyph at',
    '       the cursor (typing # or b in the input also works).',
    '    • PALETTE MODE dropdown — pick the diatonic flavour the chip row',
    '       below uses: Major, Minor, Dorian, Phrygian, Lydian, Mixolydian,',
    '       Harmonic, Melodic. Roman tokens already in the progression do',
    '       NOT change when you switch modes — only the palette does.',
    '    • ▶ Play — auditions the progression with a soft triangle-wave',
    '       synth. The sticky-header Audio (♪) toggle must be on.',
    '    • Tempo — 40–200 bpm slider. Live; updates without re-rendering.',
    '',
    '  Palette chips:',
    '    Seven Roman-numeral chips for the current mode (I, ii, iii, IV,',
    '    V, vi, vii° for major; flavours change for other modes). Click',
    '    any chip to APPEND that Roman to your progression.',
    '',
    '  The bar strip:',
    '    Each chord you add becomes a bar with three dropdowns:',
    '      DEGREE — change to a different Roman / chromatic degree.',
    '      NOTE   — pick a different root letter (turns the bar absolute).',
    '      VOICING — Maj, m, 7, m7, Maj7, m-Maj7, dim, dim7, m7♭5, aug,',
    '                sus2, sus4, 6, m6, 9, m9, Maj9, add9, 11, 13.',
    '    The ⋯ corner button opens a per-bar action menu (right now just',
    '    "Highlight on fretboard / keyboard"). The × in the corner removes',
    '    the bar. Bars can be reordered or removed without losing siblings.',
    '    The dashed + box at the end of the strip appends a new bar',
    '    pre-filled with the current key + Maj.',
    '',
    '  Section header buttons:',
    '    • Clear — clears just the progression (prog + pmode + tempo).',
    '       Does not affect the rest of the page.',
    '    • Print — prints the progression as a portrait chord chart, big',
    '       text, four bars wide.',
    '',
    '  Bookmark-friendly: prog, pmode, and tempo all live in the URL.',
    ''
  ].join('\n'),

  key_signatures: [
    '',
    '  Key Signatures',
    '  ==============',
    '',
    '  A reference table of every major key, paired with its Circle of',
    '  Fifths and a few cheat-sheet panels.',
    '',
    '  The table:',
    '    • Sharp keys on top (C, G, D, A, E, B, F♯, C♯), then flats',
    '      (F, B♭, E♭, A♭, D♭, G♭, C♭).',
    '    • Each row shows: the accidental notes in canonical order, the',
    '      key name (with its relative minor next to it — they share the',
    '      same key signature), the count of sharps or flats, the staff',
    '      with the actual accidental marks, and a hand-signal mnemonic.',
    '    • Click any row to jump to that key. The current key is',
    '      highlighted cyan.',
    '',
    '  Hand-signal mnemonic: fingers UP = sharps, fingers DOWN = flats.',
    '  Number of fingers = count. So 3 fingers up = A major (3 ♯), 2',
    '  fingers down = B♭ major (2 ♭).',
    '',
    '  Circle of Fifths:',
    '    Twelve wedges, each labelled with a major key (outer ring) and',
    '    its relative minor (inner ring). Going clockwise, each wedge is',
    '    a perfect fifth higher; going counter-clockwise, a perfect fourth.',
    '    Click any wedge to switch to that key. Three positions show',
    '    enharmonic spellings (B / C♭, F♯ / G♭, C♯ / D♭) — same pitches,',
    '    different name.',
    '',
    '  Cheat-sheet panels:',
    '    • Intervals from the current key — every interval (P1 through M7)',
    '      named, in semitones, with the resulting note.',
    '    • In <key> major — the notes, relative minor, parallel minor,',
    '      dominant key (V), and subdominant key (IV) for the current key.',
    '    • Cadences — the four most common 2-chord cadences (Authentic,',
    '      Plagal, Half, Deceptive) with audio playback.',
    ''
  ].join('\n'),

  tab: [
    '',
    '  Tab Editor',
    '  ==========',
    '',
    '  An in-page tablature editor for 4- to 12-string instruments. Type',
    '  fret numbers and articulation symbols, print finished tab, or print',
    '  a stack of empty staves for handwriting.',
    '',
    '  Setup controls (top row):',
    '    • TITLE — printed at the top of every page.',
    '    • STRINGS — 4 through 12.',
    '    • TUNING — preset tunings filtered to your string count.',
    '    • MEASURES — total length.',
    '    • BEATS / MEASURE — time signature top number.',
    '    • SUBDIVISIONS — 1 (quarters), 2 (8ths), 3 (triplets), 4 (16ths).',
    '    • MEASURES / LINE — how many bars wrap onto each printed row.',
    '',
    '  Editing:',
    '    • Type 0–99 in any cell for a fret number.',
    '    • Articulation symbols: h hammer, p pull, / slide up, \\\\ slide',
    '      down, ~ vibrato, x mute.',
    '    • Tab moves right, Enter moves down, arrow keys go anywhere.',
    '    • Edit string labels on the left edge directly. ↑ / ↓ moves',
    '      between strings; Enter drops into the first cell on that row.',
    '    • ⇅ flip strings reverses row order (highest pitch on top vs.',
    '      bottom).',
    '',
    '  Capture from fretboard:',
    '    Open the "Capture from fretboard" panel, hit ⏺ to record, then',
    '    click frets on the mini-board. Each click writes that fret number',
    '    into the cursor cell and advances. ⫳ stacks notes in the same',
    '    column (chord). ⊘ rests. ⌫ erases. ⏮ resets the cursor.',
    '',
    '  Chord boxes:',
    '    Open chord-box diagrams shown above your tab when printed. Click',
    '    a fret to add a dot, click above the box to toggle × (mute) or ○',
    '    (open string). −/+ shifts the box up or down the neck.',
    '',
    '  Print:',
    '    • PRINT BLANK — empty staves at your string count, no bar lines',
    '      (handwriting practice).',
    '    • PRINT TAB — your written tab, no chord boxes.',
    '    • PRINT BOXES — just the chord boxes.',
    '    • PRINT ALL — chord boxes + tab.',
    ''
  ].join('\n'),

  sheetmusic: [
    '',
    '  Sheet Music',
    '  ===========',
    '',
    '  A searchable library of chord progressions extracted from a 4,000+',
    '  jazz / pop fake-book collection. Each entry shows the song title,',
    '  key, time signature, and chord changes — both as concrete chord',
    '  names AND as Nashville-style scale degrees so you can transpose.',
    '',
    '  This section is currently under construction; data wiring is in',
    '  progress. The placeholder text describes what will land here once',
    '  the catalogue is published.',
    ''
  ].join('\n'),

  ear_training: [
    '',
    '  Ear Training',
    '  ============',
    '',
    '  Random interval- and chord-identification drills. The site plays a',
    '  root note and one or more follow-up notes; you guess what you heard.',
    '',
    '  Modes:',
    '    • INTERVALS — root + one other note. Pick any subset of the 12',
    '      chromatic intervals to drill (m2, M2, m3, M3, P4, TT, P5, m6,',
    '      M6, m7, M7). Buttons show the short name; hover for the long',
    '      name.',
    '    • CHORDS — root + the rest of a triad or 7th chord. Pool covers',
    '      Major, minor, diminished, augmented, dom7, Maj7, min7, m7♭5.',
    '',
    '  Playback:',
    '    • ↑ Melodic — notes one after another, low → high',
    '    • ↓ Melodic — notes one after another, high → low',
    '    • ⧉ Harmonic — every note struck at once',
    '    • ↑ then ⧉ — melodic first, then harmonic',
    '',
    '  Uses whatever instrument voice you have selected elsewhere in the',
    '  site. Score (correct / wrong) persists in localStorage and can be',
    '  reset from the score row. Pool + playback preferences persist too.',
    ''
  ].join('\n'),

  learn: [
    '',
    '  Quiz',
    '  ====',
    '',
    '  Endless random multiple-choice quiz to drill scale, chord, and key',
    '  signature recall. Every question is freshly generated — there is no',
    '  fixed bank to memorise.',
    '',
    '  Question types (rotate randomly):',
    '    • Show degrees → name the SCALE',
    '         e.g.  "1 2 ♭3 4 5 6 ♭7"  →  Dorian',
    '    • Show degrees → name the CHORD',
    '         e.g.  "1 3 5 ♭7"  →  dom7',
    '    • Show notes in a key → name the SCALE or CHORD',
    '         e.g.  "In C: C E G B"  →  Maj7',
    '    • Mode characteristic note',
    '         e.g.  "Which mode has a ♯4?"  →  Lydian',
    '    • Cadence recognition',
    '         e.g.  "V → I"  →  Authentic cadence',
    '    • Key signature drills (sharps / flats / accidental notes)',
    '',
    '  Use the SIDEBAR to enable / disable categories — your selection',
    '  persists in localStorage. Click any answer to mark it: green for',
    '  correct, red for wrong. Click NEXT for a fresh question. There is',
    '  no score and no time pressure.',
    ''
  ].join('\n')
};
